myProject/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.staticfiles.urls import staticfiles_urlpatterns


urlpatterns = [
    path('accounts/admin/', admin.site.urls, name='superuser'),    
    path('', include('blogs.urls.index')),
    path('ip/', include('blogs.urls.ip')),
    path('', include('blogs.urls.customer')),
    path('equipment/', include('blogs.urls.equipment')),
    path('service/', include('blogs.urls.service')),
    path('', include('blogs.urls.rack')),
    path('superuser/', include('blogs.urls.register')),
    path('accounts/', include('django.contrib.auth.urls')),
    path('api/', include('blogs.urls.api')),
    path('', include('blogs.urls.profile')),
    path('location/', include('blogs.urls.location')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

blogs/models/customer.py
from django.db import models

class Customer(models.Model):
    name = models.CharField(max_length=140, default='')
    email = models.EmailField()
    phone = models.CharField(max_length=140, default='')
    address = models.CharField(max_length=7000, default='')
    def __str__(self):
        return self.name

blogs/models/location.py
from django.db import models

class Location(models.Model):
    location = models.CharField(max_length=5000, default='')
    address = models.CharField(max_length=5000, default='')
    def __str__(self):
        return self.location

blogs/views/api.py
from rest_framework import viewsets
from blogs.serializers.equipment import EquipmentSerializers, RackEquipmentSerializers, EquipmentTypeSerializers, RackSerializers
from blogs.serializers.ip import IPNetworkSerializers, IPAddressSerializers
from blogs.serializers.service import ServiceTypeSerializers, ServiceSerializers, ServiceEquipmentSerializers, ServiceIPAddressSerializers
from blogs.serializers.customer import CustomerSerializers
from blogs.models.equipment import Equipment, RackEquipment, MachineType
from blogs.models.rack import Rack
from blogs.models.customer import Customer
from blogs.models.ip import IPNetworkk, IPAddresss
from blogs.models.service import ServiceIPAddress, ServiceEquipment, ServiceType, Service
from django.core.exceptions import SuspiciousOperation
from rest_framework import permissions


class EquipmentSerializersView(viewsets.ModelViewSet):
    queryset = Equipment.objects.all()
    serializer_class = EquipmentSerializers

class RackEquipmentSerializersView(viewsets.ModelViewSet):
    queryset = RackEquipment.objects.all()
    serializer_class = RackEquipmentSerializers

class MachineTypeSerializersView(viewsets.ModelViewSet):
    queryset = MachineType.objects.all()
    serializer_class = EquipmentTypeSerializers
    permission_classes = (permissions.IsAdminUser, )

class RackSerializersView(viewsets.ModelViewSet):
    queryset = Rack.objects.all()
    serializer_class = RackSerializers

###########################################################################

class IPNetworkSerializersView(viewsets.ModelViewSet):
    queryset = IPNetworkk.objects.all()
    serializer_class = IPNetworkSerializers

class IPAddressSerializersView(viewsets.ModelViewSet):
    queryset = IPAddresss.objects.all()
    serializer_class = IPAddressSerializers

###########################################################################

class ServiceTypeSerializersView(viewsets.ModelViewSet):
    queryset = ServiceType.objects.all()
    serializer_class = ServiceTypeSerializers
    permission_classes = (permissions.IsAdminUser, )

class ServiceSerializersView(viewsets.ModelViewSet):
    queryset = Service.objects.all()
    serializer_class = ServiceSerializers

class ServiceEquipmentSerializersView(viewsets.ModelViewSet):
    queryset = ServiceEquipment.objects.all()
    serializer_class = ServiceEquipmentSerializers

class ServiceIPAddressSerializersView(viewsets.ModelViewSet):
    queryset = ServiceIPAddress.objects.all()
    serializer_class = ServiceIPAddressSerializers

###########################################################################

class CustomerSerializersView(viewsets.ModelViewSet):
    queryset = Customer.objects.all()
    serializer_class = CustomerSerializers

blogs/views/customer.py
from django.shortcuts import render, redirect
from django.views.generic import CreateView, UpdateView, ListView, DetailView, DeleteView
from blogs.models.customer import Customer
from blogs.forms.customer import AddCustomerForm, UpdateCustomerForm
from django.urls import reverse_lazy
from django.http import HttpResponseRedirect, JsonResponse, HttpResponse
from blogs.models.user_data import UserData
from blogs.models.equipment import RackEquipment
from blogs.models.ip import IPAddresss
from blogs.models.service import Service


class AddCustomer(CreateView):
    model = Customer
    form_class = AddCustomerForm
    template_name = 'customer/add-customer.html'
    # ส่งข้อมูลไปหน้า html 
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        # ป้องกัน error user ที่ไม่ได้ login
        try:
            context['user_data'] = UserData.objects.get(user=self.request.user.id)
        except:
            context['user'] = UserData.objects.last()
        return context
    # หนดสิ่งที่จะเกิดขึ้นหลังกดปุ่ม submit และหลังจากตรวจสอบข้อมูลในหน้าฟอร์มเสร็จแล้ว
    def form_valid(self, form):
        form.save(True)  
        return HttpResponse('<script type="text/javascript">window.close()</script>')

        
class AddCustomerTemplateView(CreateView):
    model = Customer
    form_class = AddCustomerForm
    success_url = reverse_lazy('customer-listview')
    template_name = 'customer/add-customer-template-view.html'
    # ส่งข้อมูลไปหน้า html 
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        # ป้องกัน error user ที่ไม่ได้ login
        try:
            context['user_data'] = UserData.objects.get(user=self.request.user.id)
        except:
            context['user'] = UserData.objects.last()
        return context

class UpdateCustomerTemplateView(UpdateView):
    model = Customer
    form_class = UpdateCustomerForm
    template_name = 'customer/update-customer.html'
    # เมื่อกดเพิ่มข้อมูลและต้องการให้ไปยังหน้า detail ที่ต้องใช้ id ในการเข้าถึง
    def get_success_url(self): 
        return reverse_lazy('customer-detail', kwargs={'pk': self.kwargs['pk']})
    # ส่งข้อมูลไปหน้า html 
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        # ป้องกัน error user ที่ไม่ได้ login
        try:
            context['user_data'] = UserData.objects.get(user=self.request.user.id)
        except:
            context['user'] = UserData.objects.last()
        return context

class CustomerView(ListView):
    model = Customer
    context_object_name = 'customer'
    template_name = 'customer/customer-listview.html'
    # ส่งข้อมูลไปหน้า html 
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        # ป้องกัน error user ที่ไม่ได้ login
        try:
            context['user_data'] = UserData.objects.get(user=self.request.user.id)
        except:
            context['user'] = UserData.objects.last()
        return context

class deleteCustomer(DeleteView):
    model = Customer
    success_url = reverse_lazy('customer-listview')
    def get(self, request, *args, **kwargs):
        return self.post(request, *args, **kwargs)
        
class CustomerDetail(DetailView):
    model = Customer
    context_object_name = 'customer'
    template_name = 'customer/customer-detail.html'
    # ส่งข้อมูลไปหน้า html 
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['rackequipment'] = RackEquipment.objects.filter(equipment__customer=self.kwargs['pk'])
        context['ip_address'] = IPAddresss.objects.filter(customer=self.kwargs['pk'])
        context['service'] = Service.objects.filter(customer=self.kwargs['pk'])
        # ป้องกัน error user ที่ไม่ได้ login
        try:
            context['user_data'] = UserData.objects.get(user=self.request.user.id)
        except:
            context['user'] = UserData.objects.last()
        return context

blogs/views/equipment.py
from django.shortcuts import render, get_object_or_404
from django.views.generic import CreateView, UpdateView, ListView, DeleteView, DetailView
from blogs.models.equipment import Equipment, RackEquipment, MachineType
from blogs.models.ip import IPAddresss, IPNetworkk
from blogs.models.customer import Customer
from blogs.models.rack import Rack
from blogs.forms.equipment import AddEquipmentForm, UpdateEquipmentForm, AddEquipmentTypeForm, MoveRachForm
from django.urls import reverse_lazy
from django.http import HttpResponseRedirect, JsonResponse
from django.utils import timezone
from django.db.models import Q
from django.http import HttpResponseRedirect, JsonResponse, HttpResponse
from blogs.models.user_data import UserData
from blogs.models.location import Location


class EquipmentView(ListView):
    model = RackEquipment
    context_object_name = 'rackequipment'
    template_name = 'equipment/equipment-view.html'
    # ส่งข้อมูลไปหน้า html 
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['customer'] = Customer.objects.all()
        context['rackequipment2'] = RackEquipment.objects.all()
        context['location'] = Location.objects.all()
        context['rack'] = Rack.objects.all()
        context['user_data_all'] = UserData.objects.all()
        # ป้องกัน error user ที่ไม่ได้ login
        try:
            context['user_data'] = UserData.objects.get(user=self.request.user.id)
        except:
            context['user'] = UserData.objects.last()
        return context

class EquipmentDetail(DetailView):
    model = Equipment
    context_object_name = 'equipment'
    template_name = 'equipment/equipment-detail.html'
    # ส่งข้อมูลไปหน้า html 
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['rack_equipment'] = RackEquipment.objects.filter(equipment=self.kwargs['pk'])
        context['rackequipment'] = (RackEquipment.objects.filter(equipment=self.kwargs['pk'])).last()
        context['customer'] = Customer.objects.all()
        context['ipaddress'] = len(IPAddresss.objects.filter(equipment=self.kwargs['pk']))
        context['user_data_id'] = (UserData.objects.get(user=(Equipment.objects.get(id=self.kwargs['pk'])).user.id)).id
        context['user_data_all'] = UserData.objects.all()
        unit = ''
        for x in RackEquipment.objects.filter(equipment=self.kwargs['pk']):
            if x == (RackEquipment.objects.filter(equipment=self.kwargs['pk'])).last():
                unit = unit + x.unit_number
            else:
                unit = unit + x.unit_number + ', '
        context['unit'] = unit
        # ป้องกัน error user ที่ไม่ได้ login
        try:
            context['user_data'] = UserData.objects.get(user=self.request.user.id)
        except:
            context['user'] = UserData.objects.last()
        return context

class AddEquipment(CreateView):
    model = Equipment
    form_class = AddEquipmentForm 
    # เมื่อกดเพิ่มข้อมูลและต้องการให้ไปยังหน้า detail ที่ต้องใช้ id ในการเข้าถึง
    def get_success_url(self): 
        rackequipment = RackEquipment.objects.last()
        return reverse_lazy('equipment-detail', kwargs={'pk': rackequipment.equipment.id})
    template_name = 'equipment/add-equipment.html'
    # ส่งข้อมูลไปหน้า form
    def get_form_kwargs(self):
        kwargs = super().get_form_kwargs()
        kwargs['user'] = self.request.user
        return kwargs
    # ส่งข้อมูลไปหน้า html 
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['ip_network'] = IPNetworkk.objects.all()
        context['rack_equipment'] = RackEquipment.objects.all()
        context['rack'] = Rack.objects.all()
        context['equipment'] = Equipment.objects.last()
        context['equipment_all'] = Equipment.objects.all()
        context['customer'] = Customer.objects.all()
        context['location'] = Location.objects.all()
        # ป้องกัน error user ที่ไม่ได้ login
        try:
            context['user_data'] = UserData.objects.get(user=self.request.user.id)
        except:
            context['user'] = UserData.objects.last()
        return context

class AddEquipmentType(CreateView):
    model = MachineType
    form_class = AddEquipmentTypeForm
    template_name = 'equipment/add-type-equipment.html'
    # หนดสิ่งที่จะเกิดขึ้นหลังกดปุ่ม submit และหลังจากตรวจสอบข้อมูลในหน้าฟอร์มเสร็จแล้ว
    def form_valid(self, form):
        form.save(True)  
        return HttpResponse('<script type="text/javascript">window.close()</script>')

class MoveRack(UpdateView):
    model = Equipment
    context_object_name = 'equipment'
    form_class = MoveRachForm
    template_name = 'equipment/update-rackequipment.html'
    # เมื่อกดเพิ่มข้อมูลและต้องการให้ไปยังหน้า detail ที่ต้องใช้ id ในการเข้าถึง
    def get_success_url(self): 
        rackequipment = RackEquipment.objects.last()
        return reverse_lazy('equipment-detail', kwargs={'pk': rackequipment.equipment.id})
    # ส่งข้อมูลไปหน้า html 
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['rack_equipment'] = RackEquipment.objects.all()
        rack_equipment = (RackEquipment.objects.filter(equipment=self.kwargs['pk'])).last()
        context['rack_equipment_get'] = rack_equipment
        context['rack'] = Rack.objects.all()
        context['equipment_all'] = Equipment.objects.all()
        context['customer'] = Customer.objects.all()
        context['location'] = Location.objects.all()
        if Location.objects.filter(rack=int(rack_equipment.rack.id)):
            context['get_location'] = Location.objects.get(rack=int(rack_equipment.rack.id))
        # ป้องกัน error user ที่ไม่ได้ login
        try:
            context['user_data'] = UserData.objects.get(user=self.request.user.id)
        except:
            context['user'] = UserData.objects.last()
        return context

class updateEquipment(UpdateView):
    model = Equipment
    context_object_name = 'equipment'
    form_class = UpdateEquipmentForm
    template_name = 'equipment/update-equipment.html'
    # เมื่อกดเพิ่มข้อมูลและต้องการให้ไปยังหน้า detail ที่ต้องใช้ id ในการเข้าถึง
    def get_success_url(self): 
        return reverse_lazy('equipment-detail', kwargs={'pk': self.kwargs['pk']})
    # ส่งข้อมูลไปหน้า form
    def get_form_kwargs(self):
        kwargs = super().get_form_kwargs()
        kwargs['id'] = self.kwargs['pk']
        return kwargs
    # ส่งข้อมูลไปหน้า html 
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        rack_equipment = RackEquipment.objects.filter(equipment=self.kwargs['pk'])
        rack_id = (rack_equipment.last()).rack.id
        context['rack'] = Rack.objects.get(id=int(rack_id))
        context['rackequipment'] = RackEquipment.objects.filter(rack=int(rack_id))
        # ป้องกัน error user ที่ไม่ได้ login
        try:
            context['user_data'] = UserData.objects.get(user=self.request.user.id)
        except:
            context['user'] = UserData.objects.last()
        return context

class deleteEquipment(DeleteView):
    model = Equipment
    success_url = reverse_lazy('equipment-listview')
    def get(self, request, *args, **kwargs):
        return self.post(request, *args, **kwargs)

class EquipmentIPAddressDetail(DetailView):
    model = Equipment
    context_object_name = 'equipment'
    template_name = 'equipment/equipmentipaddress-report.html'
    # ส่งข้อมูลไปหน้า html 
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['ip_address'] = IPAddresss.objects.filter(equipment=self.kwargs['pk'])
        context['customer'] = Customer.objects.all()
        # ป้องกัน error user ที่ไม่ได้ login
        try:
            context['user_data'] = UserData.objects.get(user=self.request.user.id)
        except:
            context['user'] = UserData.objects.last()
        return context

blogs/views/index.py
from django.shortcuts import render, redirect
from django.views.generic import CreateView, UpdateView, ListView, TemplateView
from blogs.models.ip import IPNetworkk
from blogs.models.equipment import Equipment, RackEquipment
from blogs.models.service import Service
from blogs.models.rack import Rack
from blogs.models.user_data import UserData
from django.contrib.auth.models import User
from blogs.models.location import Location

class IndexView(TemplateView):
    template_name = 'index.html'
    # ส่งข้อมูลไปหน้า html 
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        try:
            if not UserData.objects.filter(user=self.request.user.id):
                UserData(user=User.objects.get(id=self.request.user.id)).save()
        except:
            print("pleass login")
        context['ipnetwork'] = IPNetworkk.objects.all()
        context['equipment'] = Equipment.objects.all()
        context['rackequipment'] = RackEquipment.objects.all()
        context['service'] = Service.objects.all()
        context['rack'] = Rack.objects.all()
        context['location'] = Location.objects.all()
        try:
            context['user_data'] = UserData.objects.get(user=self.request.user.id)
        except:
            context['user'] = UserData.objects.last()
        return context

class LinkLoginRegisterView(TemplateView):
    template_name = 'link-login-register.html'

blogs/templates/customer/add-customer-template-view.html
{% extends 'base.html' %} {% load static %} {% block content %}{% if user.is_superuser %}
<style>
    .name_error,
    .email_error,
    .phone_error,
    .address_error {
        font-size: 12px;
        color: rgb(255, 0, 0);
    }
    
    textarea {
        height: 80px;
        resize: none;
        padding: 10px 10px 10px 10px;
    }
</style>

<!-- ตรวจสอบข้อมูล user ว่ามี่การเพิ่มข้อมูลครบแล้วหรือยัง -->
{% if user_data.first_name == "" or user_data.last_name == "" or user_data.email == "" or user_data.phone == "" or user_data.address == "" or user_data.image == "" %}
<meta http-equiv=refresh content=0;URL="{% url 'profile' user.id %}"> {% endif %}

<div class="container">
    <h2>Add Customer</h2>
    <!-- ฟอร์มกรอกข้อมูล -->
    <form method="POST">
        {% csrf_token %} {{ form.as_p }}
        <input type="submit" value="Save" class="btn btn-outline-success btn-block" id="btn-add">
    </form>
</div>

<script src="https://code.jquery.com/jquery-3.4.1.min.js"></script>

<script type="text/javascript">
    // ปรับแต่งฟอร์มกรอกข้อมูล
    setLabel_input = ["Full Name", "Email", "Phone", "Address"]
    setInput_text = ["name", "email", "phone", "address"]
    var i = 0;
    while (i <= setInput_text.length) {
        $('#id_' + setInput_text[i]).addClass(setInput_text[i] + ' form-control my-0 py-1 lime-border');
        $('.' + setInput_text[i]).after('<label><p id="' + setInput_text[i] + '_error" class="' + setInput_text[i] + '_error"></p></label>');
        $('label[for="id_' + setInput_text[i] + '"]').replaceWith('<label>' + setLabel_input[i] + '</label>');
        i++
    }
    $('.errorlist').addClass("alert alert-danger");
</script>
<script type="text/javascript">
    var name = 0;
    var email = 0;
    var phone = 0;
    var address = 0;
    $(function() {
        // ตรวจสอบข้อมูลอีกครั้งหลังกดปุ่ม submit
        $("#btn-add").click(function myFunction() {
            if (validateName()) {
                $('#id_name').css("border", "2px solid rgb(252, 0, 0)");
                $("#name_error").html("ต้องมีตัวอักษร 5-50 ตัว");
                $("#name_error").show();
                name = 0;
            } else {
                $('#id_name').css("border", "2px solid dodgerblue");
                $("#name_error").hide();
                name = 1;
            }
            if (validateEmail()) {
                $('#id_email').css("border", "2px solid rgb(252, 0, 0)");
                $("#email_error").html("รูปแบบ Email ไม่ถูกต้อง");
                $("#email_error").show();
                email = 0;
            } else {
                $('#id_email').css("border", "2px solid dodgerblue");
                $("#email_error").hide();
                email = 1;
            }
            if (validatePhone()) {
                $('#id_phone').css("border", "2px solid rgb(252, 0, 0)");
                $("#phone_error").html("กรุณากรอกเบอร์โทรศัพท์");
                $("#phone_error").show();
                phone = 0;
            } else {
                $('#id_phone').css("border", "2px solid dodgerblue");
                $("#phone_error").hide();
                phone = 1;
            }
            if (validateAddress()) {
                $('#id_address').css("border", "2px solid rgb(252, 0, 0)");
                $("#address_error").html("กรุณากรอกที่อยู่");
                $("#address_error").show();
                address = 0;
            } else {
                $('#id_address').css("border", "2px solid dodgerblue");
                $("#address_error").hide();
                address = 1;
            }
            if (name == 1 && email == 1 &&
                phone == 1 && address == 1)
                return true;
            else
                return false;
        });
        // ตรวจสอบข้อมูลอีกครั้งก่อนกดปุ่ม submit
        $('#id_name').keyup(function() {
            if (validateName()) {
                $('#id_name').css("border", "2px solid rgb(252, 0, 0)");
                $("#name_error").html("ต้องมีตัวอักษรตั้งแต่ 5-50 ตัว");
                $("#name_error").show();
                name = 0;
            } else {
                $('#id_name').css("border", "2px solid dodgerblue");
                $("#name_error").hide();
                name = 1;
            }
        });
        $('#id_email').keyup(function() {
            if (validateEmail()) {
                $('#id_email').css("border", "2px solid rgb(252, 0, 0)");
                $("#email_error").html("รูปแบบ Email ไม่ถูกต้อง");
                $("#email_error").show();
                email = 0;
            } else {
                $('#id_email').css("border", "2px solid dodgerblue");
                $("#email_error").hide();
                email = 1;
            }
        });

        $('#id_phone').keyup(function() {
            if (validatePhone()) {
                $('#id_phone').css("border", "2px solid rgb(252, 0, 0)");
                $("#phone_error").html("กรุณากรอกเบอร์โทรศัพท์");
                $("#phone_error").show();
                phone = 0;
            } else {
                $('#id_phone').css("border", "2px solid dodgerblue");
                $("#phone_error").hide();
                phone = 1;
            }
        });
        $('#id_address').keyup(function() {
            if (validateAddress()) {
                $('#id_address').css("border", "2px solid rgb(252, 0, 0)");
                $("#address_error").html("ต้องมีตัวอักษร 25 ตัวขึ้นไป");
                $("#address_error").show();
                address = 0;
            } else {
                $('#id_address').css("border", "2px solid dodgerblue");
                $("#address_error").hide();
                address = 1;
            }
        });


        function validateName() {
            var name_length = $("#id_name").val().length;
            reg = /^[ ]{1}/
            if (name_length <= 0 || name_length > 50) {
                return true;
            } else {
                return false;
            }
        }

        function validateEmail() {
            var email = $("#id_email").val();
            var reg = /^\w+([-+.']\w+)*@\w+([-.]\w+)*\.\w+([-.]\w+)*$/
            if (reg.test(email)) {
                return false;
            } else {
                return true;
            }
        }

        function validatePhone() {
            var phone = $("#id_phone").val();
            var reg = /\(?([0-9]{3})\)?([ .-]?)([0-9]{3})\2([0-9]{4})/
            if (phone == "") {
                return true;
            } else {
                return false;
            }
        }

        function validateAddress() {
            var address = $("#id_address").val();
            if (address == "") {
                return true;
            } else {
                return false;
            }
        }
    });
</script>


<script>
    document.getElementById("id_name").placeholder = "Full Name";
    document.getElementById("id_email").placeholder = "Email";
    document.getElementById("id_phone").placeholder = "Phone Number";
    document.getElementById("id_address").placeholder = "Address";
</script>


{% else %}
<meta http-equiv=refresh content=0;URL="{% url 'index' %}"> {% endif %} {% endblock %}

blogs/templates/customer/customer-listview.html
{% extends 'base.html' %} {% load static %} {% block content %} {% if user.is_authenticated %}

<div style="display: none;">
    {% block title %}Customer Listview{% endblock %}
</div>

<!-- ตรวจสอบข้อมูล user ว่ามี่การเพิ่มข้อมูลครบแล้วหรือยัง -->
{% if user_data.first_name == "" or user_data.last_name == "" or user_data.email == "" or user_data.phone == "" or user_data.address == "" or user_data.image == "" %}
<meta http-equiv=refresh content=0;URL="{% url 'profile' user.id %}"> {% endif %}

<div class="container  table-responsive listview">
    <h2>Customer View</h2>
    {% if user.is_superuser %}
    <!-- ลิ้งค์ไปหน้า add customer template View -->
    <a href="{% url 'add-customer-template-view' %}" class="btn btn-outline-success add">Add Customer</a> {% endif %}
    <!-- table แสดงรายชื่อ customer -->
    <table id="myTable" class="table table-hover table-view">
        <thead>
            <tr>
                <th>Full Name</th>
                <th>Phone Number</th>
                <th>Email</th>
            </tr>
        </thead>
        <tbody id="myBody">
        </tbody>
    </table>
</div>


<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.4.1/jquery.min.js"></script>

<script>
    // ล้าง storage ที่เคยบันทึกข้อมูลไว้
    $('document').ready(function() {
        localStorage.clear();
    });
</script>

<script>
    // ลิสรายชื่อ customer
    var body = '';
    var customer = [];
    var i = 0;
    "{% for x in customer %}"
    body += '<tr>';
    body += '<td>{{x.name}}</td>';
    body += '<td>{{x.phone}}</td>';
    body += '<td>{{x.email}}</td>';
    body += "<td style='vertical-align : middle;'><a href='{% url 'customer-detail' x.id %}' class='btn btn-outline-primary'" +
        " role='button'>Detail</a></td>";
    "{% if user.is_superuser %}"
    body += "<td style='vertical-align : middle;'><a href='{% url 'delete-customer' x.id %}' onclick='return DeleteCustomer(" + i +
        ");' class='btn btn-outline-danger' role='button'>Delete</a></td>";
    "{% endif %}"
    body += '</tr>';
    customer.push("คุณต้องการลบ Customer {{x.name}}");
    i++;
    "{% endfor %}"
    $('#myBody').append(body);

    // จัดเรียงชื่อ customer ตามตัวอักษร
    var table, rows, switching, i, x, y, shouldSwitch;
    table = document.getElementById("myTable");
    switching = true;
    while (switching) {
        switching = false;
        rows = table.rows;
        for (var i = 1; i < (rows.length - 1); i++) {
            shouldSwitch = false;
            x = rows[i].getElementsByTagName("TD")[0];
            y = rows[i + 1].getElementsByTagName("TD")[0];
            if (x.innerHTML.toLowerCase() > y.innerHTML.toLowerCase()) {
                shouldSwitch = true;
                break;
            }
        }
        if (shouldSwitch) {
            rows[i].parentNode.insertBefore(rows[i + 1], rows[i]);
            switching = true;
        }
    }

    // ฟังก์ชัน่แสดงเมื่อกดปุ่ม delete
    function DeleteCustomer(id) {
        var r = confirm(customer[id]);
        if (r == true)
            return true;
        else
            return false;
    }
</script>
{% else %}

<meta http-equiv=refresh content=0;URL="{% url 'link-login-register' %}"> {% endif %} {% endblock %}

blogs/templates/customer/model-customer.html
<!-- popup ข้อมูล customer -->
{% for customer in customer reversed %}
<div class="modal fade" id="customer{{ customer.id }}" tabindex="-1" role="dialog" aria-labelledby="exampleModalLongTitle" aria-hidden="true">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="exampleModalLongTitle">Detail</h5>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
            <span aria-hidden="true">&times;</span>
          </button>
            </div>
            <div class="modal-body">
                <table align="center">
                    <tbody>
                        <tr>
                            <th>Name:</th>
                            <td>{{ customer.name }}</td>
                        </tr>
                        <tr>
                            <th>Email:</th>
                            <td>{{ customer.email }}</td>
                        </tr>
                        <tr>
                            <th>Phone:</th>
                            <td>{{ customer.phone }}</td>
                        </tr>
                        <tr>
                            <th>Address:</th>
                            <td>{{ customer.address }}</td>
                        </tr>
                    </tbody>
                </table>
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
            </div>
        </div>
    </div>
</div>
{% endfor %}