myProject/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.staticfiles.urls import staticfiles_urlpatterns


urlpatterns = [
    path('accounts/admin/', admin.site.urls, name='superuser'),    
    path('', include('blogs.urls.index')),
    path('ip/', include('blogs.urls.ip')),
    path('', include('blogs.urls.customer')),
    path('equipment/', include('blogs.urls.equipment')),
    path('service/', include('blogs.urls.service')),
    path('', include('blogs.urls.rack')),
    path('superuser/', include('blogs.urls.register')),
    path('accounts/', include('django.contrib.auth.urls')),
    path('api/', include('blogs.urls.api')),
    path('', include('blogs.urls.profile')),
    path('location/', include('blogs.urls.location')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

blogs/models/customer.py
from django.db import models

class Customer(models.Model):
    name = models.CharField(max_length=140, default='')
    email = models.EmailField()
    phone = models.CharField(max_length=140, default='')
    address = models.CharField(max_length=7000, default='')
    def __str__(self):
        return self.name

blogs/models/equipment.py
from django.db import models
from blogs.models.customer import Customer
from django.contrib.auth.models import User
from blogs.models.rack import Rack
from django.dispatch import receiver
from django.db.models.signals import pre_save, pre_delete
import os


class MachineType(models.Model):
    type_machine = models.CharField(max_length=140, default='')
    def __str__(self):
        return self.type_machine
        
class Equipment(models.Model):
    serial_number = models.CharField(max_length=140, default='')
    machine_name = models.CharField(max_length=140, default='')
    machine_type = models.ForeignKey(MachineType, on_delete=models.CASCADE)
    machine_weight = models.FloatField(max_length=140, default='')
    electric_power = models.FloatField(max_length=140, default='')
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    customer = models.ForeignKey(Customer, on_delete=models.CASCADE, blank=True, null=True) 
    image = models.ImageField(default='___/___/')
    code_type = models.CharField(max_length=140, default='', blank=True, null=True)
    code = models.CharField(max_length=1000, default='', blank=True, null=True)
    auto_generate = models.BooleanField(default=True)
    def __str__(self):
        return self.serial_number

class RackEquipment(models.Model):
    equipment = models.ForeignKey(Equipment, on_delete=models.CASCADE)
    front_back = models.CharField(max_length=500, default='')
    rack = models.ForeignKey(Rack, on_delete=models.SET_NULL, blank=True, null=True)
    unit_number = models.CharField(max_length=500, default='')
    def __str__(self):
        return self.unit_number


        
@receiver(pre_save, sender=Equipment)
def delete_old_image(sender, instance, *args, **kwargs):
    if instance.pk:
        existing_image = Equipment.objects.get(pk=instance.pk)
        if instance.image and existing_image.image != instance.image:
            existing_image.image.delete(True)

def _delete_file(path):
    if os.path.isfile(path):
        os.remove(path)

@receiver(pre_delete, sender=Equipment)
def delete_image_pre_delete_product(sender, instance, *args, **kwargs):
    if instance.image:
        _delete_file(instance.image.path)

blogs/models/location.py
from django.db import models

class Location(models.Model):
    location = models.CharField(max_length=5000, default='')
    address = models.CharField(max_length=5000, default='')
    def __str__(self):
        return self.location

blogs/models/rack.py
from django.db import models
from blogs.models.location import Location

class Rack(models.Model):
    location = models.ForeignKey(Location, on_delete=models.CASCADE)
    rack = models.CharField(max_length=140, default='')
    acceptable_weight = models.FloatField()
    rack_weight = models.FloatField()
    rack_size = models.IntegerField()
    def __str__(self):
        return self.rack

blogs/models/user_data.py
from django.db import models
from blogs.models.customer import Customer
from django.contrib.auth.models import User
from blogs.models.rack import Rack
from django.dispatch import receiver
from django.db.models.signals import pre_save, pre_delete
import os


class UserData(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE) 
    first_name = models.CharField(max_length=1000, default='', blank=True, null=True)
    last_name = models.CharField(max_length=1000, default='', blank=True, null=True)
    email = models.CharField(max_length=1000, default='', blank=True, null=True)
    phone = models.CharField(max_length=1000, default='', blank=True, null=True)
    address = models.TextField(default='', blank=True, null=True)
    image = models.ImageField(blank=True, null=True)
    def __str__(self):
        return self.user.username


        
@receiver(pre_save, sender=UserData)
def delete_old_image(sender, instance, *args, **kwargs):
    if instance.pk:
        existing_image = UserData.objects.get(pk=instance.pk)
        if instance.image and existing_image.image != instance.image:
            existing_image.image.delete(True)

def _delete_file(path):
    if os.path.isfile(path):
        os.remove(path)

@receiver(pre_delete, sender=UserData)
def delete_image_pre_delete_product(sender, instance, *args, **kwargs):
    if instance.image:
        _delete_file(instance.image.path)

blogs/forms/customer.py
from django import forms
from blogs.models.customer import Customer


class AddCustomerForm(forms.ModelForm):

    address = forms.CharField(widget=forms.Textarea)

    class Meta:

        model = Customer
        fields = (
                    'name',
                    'email',
                    'phone',
                    'address',
                 )

    def clean_name(self, *args, **kwargs):
        name_input = self.cleaned_data.get('name')
        # ตวจสอบว่ามี Customer ที่ใช้ชื่อนี้แล้วหรือยัง
        if(Customer.objects.filter(name=name_input)):
            self._errors['name'] = self.error_class(['**ท่านเคยลงทะเบียนแล้ว']) 
        return name_input

    def clean_address(self, *args, **kwargs):
        # รับข้อมูลและเก็บข้อมูลเป็น Array
        address_input = (self.cleaned_data.get('address')).split('\r\n')
        address = ''
        # จัดรียง Address ใหม่ให้เรียงเป็นแถวเดียวกัน
        for x in address_input:
            address = address + x + ' '
        return address

class UpdateCustomerForm(forms.ModelForm):

    address = forms.CharField(widget=forms.Textarea)

    class Meta:

        model = Customer
        fields = (
                    'name',
                    'email',
                    'phone',
                    'address',
                 )

blogs/views/api.py
from rest_framework import viewsets
from blogs.serializers.equipment import EquipmentSerializers, RackEquipmentSerializers, EquipmentTypeSerializers, RackSerializers
from blogs.serializers.ip import IPNetworkSerializers, IPAddressSerializers
from blogs.serializers.service import ServiceTypeSerializers, ServiceSerializers, ServiceEquipmentSerializers, ServiceIPAddressSerializers
from blogs.serializers.customer import CustomerSerializers
from blogs.models.equipment import Equipment, RackEquipment, MachineType
from blogs.models.rack import Rack
from blogs.models.customer import Customer
from blogs.models.ip import IPNetworkk, IPAddresss
from blogs.models.service import ServiceIPAddress, ServiceEquipment, ServiceType, Service
from django.core.exceptions import SuspiciousOperation
from rest_framework import permissions


class EquipmentSerializersView(viewsets.ModelViewSet):
    queryset = Equipment.objects.all()
    serializer_class = EquipmentSerializers

class RackEquipmentSerializersView(viewsets.ModelViewSet):
    queryset = RackEquipment.objects.all()
    serializer_class = RackEquipmentSerializers

class MachineTypeSerializersView(viewsets.ModelViewSet):
    queryset = MachineType.objects.all()
    serializer_class = EquipmentTypeSerializers
    permission_classes = (permissions.IsAdminUser, )

class RackSerializersView(viewsets.ModelViewSet):
    queryset = Rack.objects.all()
    serializer_class = RackSerializers

###########################################################################

class IPNetworkSerializersView(viewsets.ModelViewSet):
    queryset = IPNetworkk.objects.all()
    serializer_class = IPNetworkSerializers

class IPAddressSerializersView(viewsets.ModelViewSet):
    queryset = IPAddresss.objects.all()
    serializer_class = IPAddressSerializers

###########################################################################

class ServiceTypeSerializersView(viewsets.ModelViewSet):
    queryset = ServiceType.objects.all()
    serializer_class = ServiceTypeSerializers
    permission_classes = (permissions.IsAdminUser, )

class ServiceSerializersView(viewsets.ModelViewSet):
    queryset = Service.objects.all()
    serializer_class = ServiceSerializers

class ServiceEquipmentSerializersView(viewsets.ModelViewSet):
    queryset = ServiceEquipment.objects.all()
    serializer_class = ServiceEquipmentSerializers

class ServiceIPAddressSerializersView(viewsets.ModelViewSet):
    queryset = ServiceIPAddress.objects.all()
    serializer_class = ServiceIPAddressSerializers

###########################################################################

class CustomerSerializersView(viewsets.ModelViewSet):
    queryset = Customer.objects.all()
    serializer_class = CustomerSerializers

blogs/views/customer.py
from django.shortcuts import render, redirect
from django.views.generic import CreateView, UpdateView, ListView, DetailView, DeleteView
from blogs.models.customer import Customer
from blogs.forms.customer import AddCustomerForm, UpdateCustomerForm
from django.urls import reverse_lazy
from django.http import HttpResponseRedirect, JsonResponse, HttpResponse
from blogs.models.user_data import UserData
from blogs.models.equipment import RackEquipment
from blogs.models.ip import IPAddresss
from blogs.models.service import Service


class AddCustomer(CreateView):
    model = Customer
    form_class = AddCustomerForm
    template_name = 'customer/add-customer.html'
    # ส่งข้อมูลไปหน้า html 
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        # ป้องกัน error user ที่ไม่ได้ login
        try:
            context['user_data'] = UserData.objects.get(user=self.request.user.id)
        except:
            context['user'] = UserData.objects.last()
        return context
    # หนดสิ่งที่จะเกิดขึ้นหลังกดปุ่ม submit และหลังจากตรวจสอบข้อมูลในหน้าฟอร์มเสร็จแล้ว
    def form_valid(self, form):
        form.save(True)  
        return HttpResponse('<script type="text/javascript">window.close()</script>')

        
class AddCustomerTemplateView(CreateView):
    model = Customer
    form_class = AddCustomerForm
    success_url = reverse_lazy('customer-listview')
    template_name = 'customer/add-customer-template-view.html'
    # ส่งข้อมูลไปหน้า html 
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        # ป้องกัน error user ที่ไม่ได้ login
        try:
            context['user_data'] = UserData.objects.get(user=self.request.user.id)
        except:
            context['user'] = UserData.objects.last()
        return context

class UpdateCustomerTemplateView(UpdateView):
    model = Customer
    form_class = UpdateCustomerForm
    template_name = 'customer/update-customer.html'
    # เมื่อกดเพิ่มข้อมูลและต้องการให้ไปยังหน้า detail ที่ต้องใช้ id ในการเข้าถึง
    def get_success_url(self): 
        return reverse_lazy('customer-detail', kwargs={'pk': self.kwargs['pk']})
    # ส่งข้อมูลไปหน้า html 
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        # ป้องกัน error user ที่ไม่ได้ login
        try:
            context['user_data'] = UserData.objects.get(user=self.request.user.id)
        except:
            context['user'] = UserData.objects.last()
        return context

class CustomerView(ListView):
    model = Customer
    context_object_name = 'customer'
    template_name = 'customer/customer-listview.html'
    # ส่งข้อมูลไปหน้า html 
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        # ป้องกัน error user ที่ไม่ได้ login
        try:
            context['user_data'] = UserData.objects.get(user=self.request.user.id)
        except:
            context['user'] = UserData.objects.last()
        return context

class deleteCustomer(DeleteView):
    model = Customer
    success_url = reverse_lazy('customer-listview')
    def get(self, request, *args, **kwargs):
        return self.post(request, *args, **kwargs)
        
class CustomerDetail(DetailView):
    model = Customer
    context_object_name = 'customer'
    template_name = 'customer/customer-detail.html'
    # ส่งข้อมูลไปหน้า html 
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['rackequipment'] = RackEquipment.objects.filter(equipment__customer=self.kwargs['pk'])
        context['ip_address'] = IPAddresss.objects.filter(customer=self.kwargs['pk'])
        context['service'] = Service.objects.filter(customer=self.kwargs['pk'])
        # ป้องกัน error user ที่ไม่ได้ login
        try:
            context['user_data'] = UserData.objects.get(user=self.request.user.id)
        except:
            context['user'] = UserData.objects.last()
        return context

blogs/views/index.py
from django.shortcuts import render, redirect
from django.views.generic import CreateView, UpdateView, ListView, TemplateView
from blogs.models.ip import IPNetworkk
from blogs.models.equipment import Equipment, RackEquipment
from blogs.models.service import Service
from blogs.models.rack import Rack
from blogs.models.user_data import UserData
from django.contrib.auth.models import User
from blogs.models.location import Location

class IndexView(TemplateView):
    template_name = 'index.html'
    # ส่งข้อมูลไปหน้า html 
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        try:
            if not UserData.objects.filter(user=self.request.user.id):
                UserData(user=User.objects.get(id=self.request.user.id)).save()
        except:
            print("pleass login")
        context['ipnetwork'] = IPNetworkk.objects.all()
        context['equipment'] = Equipment.objects.all()
        context['rackequipment'] = RackEquipment.objects.all()
        context['service'] = Service.objects.all()
        context['rack'] = Rack.objects.all()
        context['location'] = Location.objects.all()
        try:
            context['user_data'] = UserData.objects.get(user=self.request.user.id)
        except:
            context['user'] = UserData.objects.last()
        return context

class LinkLoginRegisterView(TemplateView):
    template_name = 'link-login-register.html'

blogs/views/location.py
from django.views.generic import CreateView, UpdateView, ListView, DetailView, DeleteView
from blogs.forms.location import AddLocationForm, UpdateLocationForm
from django.urls import reverse_lazy
from blogs.models.user_data import UserData
from django.http import HttpResponseRedirect, JsonResponse, HttpResponse
from blogs.models.location import Location
from blogs.models.equipment import RackEquipment
from blogs.models.rack import Rack

class AddLocationTamplateView(CreateView):
    model = Location
    form_class = AddLocationForm
    template_name = 'location/add-location-tamplateview.html'
    success_url = reverse_lazy('location-listview')
    # ส่งข้อมูลไปหน้า html 
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        # ป้องกัน error user ที่ไม่ได้ login
        try:
            context['user_data'] = UserData.objects.get(user=self.request.user.id)
        except:
            context['user'] = UserData.objects.last()
        return context

class UpdateLocation(UpdateView):
    model = Location
    form_class = UpdateLocationForm
    template_name = 'location/update-location.html'
    success_url = reverse_lazy('location-listview')
    # ส่งข้อมูลไปหน้า form
    def get_form_kwargs(self):
        kwargs = super().get_form_kwargs()
        kwargs['id'] = self.kwargs['pk']
        return kwargs
    # ส่งข้อมูลไปหน้า html 
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        # ป้องกัน error user ที่ไม่ได้ login
        try:
            context['user_data'] = UserData.objects.get(user=self.request.user.id)
        except:
            context['user'] = UserData.objects.last()
        return context



class LocationView(ListView):
    model = Location
    context_object_name = 'location'
    template_name = 'location/location-listview.html'
    # ส่งข้อมูลไปหน้า html 
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['rack_equipment'] = RackEquipment.objects.all()
        context['rack'] = Rack.objects.all()
        # ป้องกัน error user ที่ไม่ได้ login
        try:
            context['user_data'] = UserData.objects.get(user=self.request.user.id)
        except:
            context['user'] = UserData.objects.last()
        return context

class deleteLocation(DeleteView):
    model = Location
    success_url = reverse_lazy('location-listview')
    def get(self, request, *args, **kwargs):
        return self.post(request, *args, **kwargs)

blogs/templates/profile/update-profile.html
{% extends 'base.html' %} {% block content %} {% if user.id == user_data.user.id%}
<style>
    ._username_error,
    ._password1_error,
    ._password2_error,
    ._first_name_error,
    ._last_name_error,
    ._email_error,
    ._phone_error,
    ._address_error,
    .profile_image_error {
        font-size: 12px;
        color: rgb(255, 0, 0);
    }
    
    .helptext {
        display: none;
    }
    
    .registerForm ul li {
        display: none;
    }
    
    form ul li {
        display: none;
    }
    
    .errorlist li {
        display: block;
    }
    
    textarea {
        resize: none;
    }
</style>
<div style="display: none;">
    {% block title %}Edit Profile{% endblock %}
</div>

<div class="container">
    <h2>Edit Profile</h2>
    <!-- ฟอร์มกรอกข้อมูล -->
    <form method="POST" enctype="multipart/form-data">
        {% csrf_token %} {{ form.as_p }}
        <input type="submit" value="Save" class="btn btn-outline-success btn-block" id="btn-add">
    </form>
</div>

<script src="https://code.jquery.com/jquery-3.4.1.min.js"></script>

<script type="text/javascript">
    // ปรับแต่งฟอร์มกรอกข้อมูล
    setLabel_input = ["Username", "Password", "Password Confirmation",
        "First Name", "Last Name", "Email", "Phone", "Address"
    ]
    setInput_text = ["username", "password1", "password2",
        "first_name", "last_name", "email", "phone", "address"
    ]
    var i = 0;
    while (i <= setInput_text.length) {
        $('#id_' + setInput_text[i]).addClass(setInput_text[i] +
            ' form-control my-0 py-1 lime-border');
        $('.' + setInput_text[i]).after('<label><p id="' +
            setInput_text[i] + '_error" class="_' + setInput_text[i] + '_error"></p></label>');
        $('label[for="id_' + setInput_text[i] + '"]').replaceWith('<label>' +
            setLabel_input[i] + '</label>');
        i++
    }
</script>


<script type="text/javascript">
    var username = 0;
    var password = 0;
    var first_name = 0;
    var last_name = 0;
    var email = 0;
    var password1;
    var phone = 0;
    var address = 0;
    $(function() {

        // ตรวจสอบข้อมูลอีกครั้งก่อนกดปุ่ม submit
        $("#btn-add").click(function() {
            if (validateFirstName()) {
                $('#id_first_name').css("border", "2px solid rgb(252, 0, 0)");
                $("#first_name_error").html("ห้ามใช้ตัวอักษรพิเศษ");
                $("#first_name_error").show();
                first_name = 0;
            } else {
                $('#id_first_name').css("border", "2px solid dodgerblue");
                $("#first_name_error").hide();
                first_name = 1;
            }
            if (validateLastName()) {
                $('#id_last_name').css("border", "2px solid rgb(252, 0, 0)");
                $("#last_name_error").html("ห้ามใช้ตัวอักษรพิเศษหรือตัวเลข");
                $("#last_name_error").show();
                last_name = 0;
            } else {
                $('#id_last_name').css("border", "2px solid dodgerblue");
                $("#last_name_error").hide();
                last_name = 1;
            }
            if (validateEmail()) {
                $('#id_email').css("border", "2px solid rgb(252, 0, 0)");
                $("#email_error").html("รูปแบบ Email ไม่ถูกต้อง");
                $("#email_error").show();
                email = 0;
            } else {
                $('#id_email').css("border", "2px solid dodgerblue");
                $("#email_error").hide();
                email = 1;
            }
            if (validatePhone()) {
                $('#id_phone').css("border", "2px solid rgb(252, 0, 0)");
                $("#phone_error").html("กรุณากรอกเบอร์โทรศัพท์");
                $("#phone_error").show();
                phone = 0;
            } else {
                $('#id_phone').css("border", "2px solid dodgerblue");
                $("#phone_error").hide();
                phone = 1;
            }
            if (validateAddress()) {
                $('#id_address').css("border", "2px solid rgb(252, 0, 0)");
                $("#address_error").html("กรุณากรอกที่อยู่");
                $("#address_error").show();
                address = 0;
            } else {
                $('#id_address').css("border", "2px solid dodgerblue");
                $("#address_error").hide();
                address = 1;
            }
            if (username == 1 && password == 1 && first_name == 1 && last_name == 1 &&
                email == 1, phone == 1 && address == 1)
                return true;
            else
                return false;

        });

        // ตรวจสอบข้อมูลอีกครั้งก่อนกดปุ่ม submit
        $('#id_first_name').keyup(function() {
            if (validateFirstName()) {
                $('#id_first_name').css("border", "2px solid rgb(252, 0, 0)");
                $("#first_name_error").html("ห้ามใช้ตัวอักษรพิเศษหรือตัวเลข");
                $("#first_name_error").show();
                first_name = 0;
            } else {
                $('#id_first_name').css("border", "2px solid dodgerblue");
                $("#first_name_error").hide();
                first_name = 1;
            }
        });

        function validateFirstName() {
            var firstname = $("#id_first_name").val();
            var reg = /[\!\@\#\$\%\^\&\฿\*\(\)\-\=\}\{\[\]\?\/\\\>\<\?\.\,\๐\'\"\+\;\:\_\0-9\ ]/g
            if (reg.test(firstname) || firstname == "") {
                return true;
            } else {
                return false;
            }
        }

        $('#id_last_name').keyup(function() {
            if (validateLastName()) {
                $('#id_last_name').css("border", "2px solid rgb(252, 0, 0)");
                $("#last_name_error").html("ห้ามใช้ตัวอักษรพิเศษ");
                $("#last_name_error").show();
                last_name = 0;
            } else {
                $('#id_last_name').css("border", "2px solid dodgerblue");
                $("#last_name_error").hide();
                last_name = 1;
            }
        });

        function validateLastName() {
            var lastname = $("#id_last_name").val();
            var reg = /[\!\@\#\$\%\^\&\฿\*\(\)\-\=\}\{\[\]\?\/\\\>\<\?\.\,\๐\'\"\+\;\:\_\0-9\ ]/g
            if (reg.test(lastname) || lastname == "") {
                return true;
            } else {
                return false;
            }
        }

        $('#id_email').keyup(function() {
            if (validateEmail()) {
                $('#id_email').css("border", "2px solid rgb(252, 0, 0)");
                $("#email_error").html("รูปแบบ Email ไม่ถูกต้อง");
                $("#email_error").show();
                email = 0;
            } else {
                $('#id_email').css("border", "2px solid dodgerblue");
                $("#email_error").hide();
                email = 1;
            }
        });

        function validateEmail() {
            var email = $("#id_email").val();
            var reg = /^\w+([-+.']\w+)*@\w+([-.]\w+)*\.\w+([-.]\w+)*$/
            if (reg.test(email)) {
                return false;
            } else {
                return true;
            }
        }

        $('#id_phone').keyup(function() {
            if (validatePhone()) {
                $('#id_phone').css("border", "2px solid rgb(252, 0, 0)");
                $("#phone_error").html("กรุณากรอกเบอร์โทรศัพท์");
                $("#phone_error").show();
                phone = 0;
            } else {
                $('#id_phone').css("border", "2px solid dodgerblue");
                $("#phone_error").hide();
                phone = 1;
            }
        });

        function validatePhone() {
            var phone = $("#id_phone").val();
            if (phone == "") {
                return true;
            } else {
                return false;
            }
        }

        $('#id_address').keyup(function() {
            if (validateAddress()) {
                $('#id_address').css("border", "2px solid rgb(252, 0, 0)");
                $("#address_error").html("กรุณากรอกที่อยู่");
                $("#address_error").show();
                address = 0;
            } else {
                $('#id_address').css("border", "2px solid dodgerblue");
                $("#address_error").hide();
                address = 1;
            }
        });

        function validateAddress() {
            var address = $("#id_address").val();
            if (address == "") {
                return true;
            } else {
                return false;
            }
        }

    });
</script>

{% else %}

<meta http-equiv=refresh content=0;URL="{% url 'index' %}"> {% endif %} {% endblock %}