myProject/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.staticfiles.urls import staticfiles_urlpatterns


urlpatterns = [
    path('accounts/admin/', admin.site.urls, name='superuser'),    
    path('', include('blogs.urls.index')),
    path('ip/', include('blogs.urls.ip')),
    path('', include('blogs.urls.customer')),
    path('equipment/', include('blogs.urls.equipment')),
    path('service/', include('blogs.urls.service')),
    path('', include('blogs.urls.rack')),
    path('superuser/', include('blogs.urls.register')),
    path('accounts/', include('django.contrib.auth.urls')),
    path('api/', include('blogs.urls.api')),
    path('', include('blogs.urls.profile')),
    path('location/', include('blogs.urls.location')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

blogs/models/equipment.py
from django.db import models
from blogs.models.customer import Customer
from django.contrib.auth.models import User
from blogs.models.rack import Rack
from django.dispatch import receiver
from django.db.models.signals import pre_save, pre_delete
import os


class MachineType(models.Model):
    type_machine = models.CharField(max_length=140, default='')
    def __str__(self):
        return self.type_machine
        
class Equipment(models.Model):
    serial_number = models.CharField(max_length=140, default='')
    machine_name = models.CharField(max_length=140, default='')
    machine_type = models.ForeignKey(MachineType, on_delete=models.CASCADE)
    machine_weight = models.FloatField(max_length=140, default='')
    electric_power = models.FloatField(max_length=140, default='')
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    customer = models.ForeignKey(Customer, on_delete=models.CASCADE, blank=True, null=True) 
    image = models.ImageField(default='___/___/')
    code_type = models.CharField(max_length=140, default='', blank=True, null=True)
    code = models.CharField(max_length=1000, default='', blank=True, null=True)
    auto_generate = models.BooleanField(default=True)
    def __str__(self):
        return self.serial_number

class RackEquipment(models.Model):
    equipment = models.ForeignKey(Equipment, on_delete=models.CASCADE)
    front_back = models.CharField(max_length=500, default='')
    rack = models.ForeignKey(Rack, on_delete=models.SET_NULL, blank=True, null=True)
    unit_number = models.CharField(max_length=500, default='')
    def __str__(self):
        return self.unit_number


        
@receiver(pre_save, sender=Equipment)
def delete_old_image(sender, instance, *args, **kwargs):
    if instance.pk:
        existing_image = Equipment.objects.get(pk=instance.pk)
        if instance.image and existing_image.image != instance.image:
            existing_image.image.delete(True)

def _delete_file(path):
    if os.path.isfile(path):
        os.remove(path)

@receiver(pre_delete, sender=Equipment)
def delete_image_pre_delete_product(sender, instance, *args, **kwargs):
    if instance.image:
        _delete_file(instance.image.path)

blogs/models/location.py
from django.db import models

class Location(models.Model):
    location = models.CharField(max_length=5000, default='')
    address = models.CharField(max_length=5000, default='')
    def __str__(self):
        return self.location

blogs/models/rack.py
from django.db import models
from blogs.models.location import Location

class Rack(models.Model):
    location = models.ForeignKey(Location, on_delete=models.CASCADE)
    rack = models.CharField(max_length=140, default='')
    acceptable_weight = models.FloatField()
    rack_weight = models.FloatField()
    rack_size = models.IntegerField()
    def __str__(self):
        return self.rack

blogs/forms/customer.py
from django import forms
from blogs.models.customer import Customer


class AddCustomerForm(forms.ModelForm):

    address = forms.CharField(widget=forms.Textarea)

    class Meta:

        model = Customer
        fields = (
                    'name',
                    'email',
                    'phone',
                    'address',
                 )

    def clean_name(self, *args, **kwargs):
        name_input = self.cleaned_data.get('name')
        # ตวจสอบว่ามี Customer ที่ใช้ชื่อนี้แล้วหรือยัง
        if(Customer.objects.filter(name=name_input)):
            self._errors['name'] = self.error_class(['**ท่านเคยลงทะเบียนแล้ว']) 
        return name_input

    def clean_address(self, *args, **kwargs):
        # รับข้อมูลและเก็บข้อมูลเป็น Array
        address_input = (self.cleaned_data.get('address')).split('\r\n')
        address = ''
        # จัดรียง Address ใหม่ให้เรียงเป็นแถวเดียวกัน
        for x in address_input:
            address = address + x + ' '
        return address

class UpdateCustomerForm(forms.ModelForm):

    address = forms.CharField(widget=forms.Textarea)

    class Meta:

        model = Customer
        fields = (
                    'name',
                    'email',
                    'phone',
                    'address',
                 )

blogs/forms/register.py
from django import forms
from django.contrib.auth.models import User
from django.contrib.auth.forms import UserCreationForm
from blogs.models.user_data import UserData

class RegistrationForm(UserCreationForm):

    user_status = forms.CharField()
    class Meta:
        model = User
        fields = (
                   'username',
                   'password1',
                   'password2',
                   'first_name',
                   'last_name',
                   'email',
                   'user_status',
                 )
    def clean_username(self, *args, **kwargs):
        username_input = self.cleaned_data.get('username')
        # ตวจสอบว่ามี user ที่ใช้ username นี้แล้วหรือยัง
        if User.objects.filter(username=username_input):
            self._errors['username'] = self.error_class(['**Username นี้เคยลงทะเบียนแล้ว']) 
        return username_input

class UpdateImageForm(forms.ModelForm):

    # รับข้อมูลจากหน้า View
    def __init__(self, *args, **kwargs):
        self.user_data_id = kwargs.pop('user_data_id', None)
        super(UpdateImageForm, self).__init__(*args, **kwargs)

    class Meta:
        model = UserData
        fields = (
                    'image',
                 )
    def save(self):
        # save image ที่เป็นรูปโปรไฟล์
        user_data = UserData.objects.get(id=int(self.user_data_id))
        user_data.image = self.cleaned_data['image']
        user_data.save()


class UpdateUserDataForm(forms.ModelForm):

    class Meta:
        model = UserData
        fields = (
                    'first_name',
                    'last_name',
                    'email',
                    'phone',
                    'address',
                 )

blogs/views/api.py
from rest_framework import viewsets
from blogs.serializers.equipment import EquipmentSerializers, RackEquipmentSerializers, EquipmentTypeSerializers, RackSerializers
from blogs.serializers.ip import IPNetworkSerializers, IPAddressSerializers
from blogs.serializers.service import ServiceTypeSerializers, ServiceSerializers, ServiceEquipmentSerializers, ServiceIPAddressSerializers
from blogs.serializers.customer import CustomerSerializers
from blogs.models.equipment import Equipment, RackEquipment, MachineType
from blogs.models.rack import Rack
from blogs.models.customer import Customer
from blogs.models.ip import IPNetworkk, IPAddresss
from blogs.models.service import ServiceIPAddress, ServiceEquipment, ServiceType, Service
from django.core.exceptions import SuspiciousOperation
from rest_framework import permissions


class EquipmentSerializersView(viewsets.ModelViewSet):
    queryset = Equipment.objects.all()
    serializer_class = EquipmentSerializers

class RackEquipmentSerializersView(viewsets.ModelViewSet):
    queryset = RackEquipment.objects.all()
    serializer_class = RackEquipmentSerializers

class MachineTypeSerializersView(viewsets.ModelViewSet):
    queryset = MachineType.objects.all()
    serializer_class = EquipmentTypeSerializers
    permission_classes = (permissions.IsAdminUser, )

class RackSerializersView(viewsets.ModelViewSet):
    queryset = Rack.objects.all()
    serializer_class = RackSerializers

###########################################################################

class IPNetworkSerializersView(viewsets.ModelViewSet):
    queryset = IPNetworkk.objects.all()
    serializer_class = IPNetworkSerializers

class IPAddressSerializersView(viewsets.ModelViewSet):
    queryset = IPAddresss.objects.all()
    serializer_class = IPAddressSerializers

###########################################################################

class ServiceTypeSerializersView(viewsets.ModelViewSet):
    queryset = ServiceType.objects.all()
    serializer_class = ServiceTypeSerializers
    permission_classes = (permissions.IsAdminUser, )

class ServiceSerializersView(viewsets.ModelViewSet):
    queryset = Service.objects.all()
    serializer_class = ServiceSerializers

class ServiceEquipmentSerializersView(viewsets.ModelViewSet):
    queryset = ServiceEquipment.objects.all()
    serializer_class = ServiceEquipmentSerializers

class ServiceIPAddressSerializersView(viewsets.ModelViewSet):
    queryset = ServiceIPAddress.objects.all()
    serializer_class = ServiceIPAddressSerializers

###########################################################################

class CustomerSerializersView(viewsets.ModelViewSet):
    queryset = Customer.objects.all()
    serializer_class = CustomerSerializers

blogs/views/customer.py
from django.shortcuts import render, redirect
from django.views.generic import CreateView, UpdateView, ListView, DetailView, DeleteView
from blogs.models.customer import Customer
from blogs.forms.customer import AddCustomerForm, UpdateCustomerForm
from django.urls import reverse_lazy
from django.http import HttpResponseRedirect, JsonResponse, HttpResponse
from blogs.models.user_data import UserData
from blogs.models.equipment import RackEquipment
from blogs.models.ip import IPAddresss
from blogs.models.service import Service


class AddCustomer(CreateView):
    model = Customer
    form_class = AddCustomerForm
    template_name = 'customer/add-customer.html'
    # ส่งข้อมูลไปหน้า html 
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        # ป้องกัน error user ที่ไม่ได้ login
        try:
            context['user_data'] = UserData.objects.get(user=self.request.user.id)
        except:
            context['user'] = UserData.objects.last()
        return context
    # หนดสิ่งที่จะเกิดขึ้นหลังกดปุ่ม submit และหลังจากตรวจสอบข้อมูลในหน้าฟอร์มเสร็จแล้ว
    def form_valid(self, form):
        form.save(True)  
        return HttpResponse('<script type="text/javascript">window.close()</script>')

        
class AddCustomerTemplateView(CreateView):
    model = Customer
    form_class = AddCustomerForm
    success_url = reverse_lazy('customer-listview')
    template_name = 'customer/add-customer-template-view.html'
    # ส่งข้อมูลไปหน้า html 
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        # ป้องกัน error user ที่ไม่ได้ login
        try:
            context['user_data'] = UserData.objects.get(user=self.request.user.id)
        except:
            context['user'] = UserData.objects.last()
        return context

class UpdateCustomerTemplateView(UpdateView):
    model = Customer
    form_class = UpdateCustomerForm
    template_name = 'customer/update-customer.html'
    # เมื่อกดเพิ่มข้อมูลและต้องการให้ไปยังหน้า detail ที่ต้องใช้ id ในการเข้าถึง
    def get_success_url(self): 
        return reverse_lazy('customer-detail', kwargs={'pk': self.kwargs['pk']})
    # ส่งข้อมูลไปหน้า html 
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        # ป้องกัน error user ที่ไม่ได้ login
        try:
            context['user_data'] = UserData.objects.get(user=self.request.user.id)
        except:
            context['user'] = UserData.objects.last()
        return context

class CustomerView(ListView):
    model = Customer
    context_object_name = 'customer'
    template_name = 'customer/customer-listview.html'
    # ส่งข้อมูลไปหน้า html 
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        # ป้องกัน error user ที่ไม่ได้ login
        try:
            context['user_data'] = UserData.objects.get(user=self.request.user.id)
        except:
            context['user'] = UserData.objects.last()
        return context

class deleteCustomer(DeleteView):
    model = Customer
    success_url = reverse_lazy('customer-listview')
    def get(self, request, *args, **kwargs):
        return self.post(request, *args, **kwargs)
        
class CustomerDetail(DetailView):
    model = Customer
    context_object_name = 'customer'
    template_name = 'customer/customer-detail.html'
    # ส่งข้อมูลไปหน้า html 
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['rackequipment'] = RackEquipment.objects.filter(equipment__customer=self.kwargs['pk'])
        context['ip_address'] = IPAddresss.objects.filter(customer=self.kwargs['pk'])
        context['service'] = Service.objects.filter(customer=self.kwargs['pk'])
        # ป้องกัน error user ที่ไม่ได้ login
        try:
            context['user_data'] = UserData.objects.get(user=self.request.user.id)
        except:
            context['user'] = UserData.objects.last()
        return context

blogs/views/index.py
from django.shortcuts import render, redirect
from django.views.generic import CreateView, UpdateView, ListView, TemplateView
from blogs.models.ip import IPNetworkk
from blogs.models.equipment import Equipment, RackEquipment
from blogs.models.service import Service
from blogs.models.rack import Rack
from blogs.models.user_data import UserData
from django.contrib.auth.models import User
from blogs.models.location import Location

class IndexView(TemplateView):
    template_name = 'index.html'
    # ส่งข้อมูลไปหน้า html 
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        try:
            if not UserData.objects.filter(user=self.request.user.id):
                UserData(user=User.objects.get(id=self.request.user.id)).save()
        except:
            print("pleass login")
        context['ipnetwork'] = IPNetworkk.objects.all()
        context['equipment'] = Equipment.objects.all()
        context['rackequipment'] = RackEquipment.objects.all()
        context['service'] = Service.objects.all()
        context['rack'] = Rack.objects.all()
        context['location'] = Location.objects.all()
        try:
            context['user_data'] = UserData.objects.get(user=self.request.user.id)
        except:
            context['user'] = UserData.objects.last()
        return context

class LinkLoginRegisterView(TemplateView):
    template_name = 'link-login-register.html'

blogs/views/location.py
from django.views.generic import CreateView, UpdateView, ListView, DetailView, DeleteView
from blogs.forms.location import AddLocationForm, UpdateLocationForm
from django.urls import reverse_lazy
from blogs.models.user_data import UserData
from django.http import HttpResponseRedirect, JsonResponse, HttpResponse
from blogs.models.location import Location
from blogs.models.equipment import RackEquipment
from blogs.models.rack import Rack

class AddLocationTamplateView(CreateView):
    model = Location
    form_class = AddLocationForm
    template_name = 'location/add-location-tamplateview.html'
    success_url = reverse_lazy('location-listview')
    # ส่งข้อมูลไปหน้า html 
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        # ป้องกัน error user ที่ไม่ได้ login
        try:
            context['user_data'] = UserData.objects.get(user=self.request.user.id)
        except:
            context['user'] = UserData.objects.last()
        return context

class UpdateLocation(UpdateView):
    model = Location
    form_class = UpdateLocationForm
    template_name = 'location/update-location.html'
    success_url = reverse_lazy('location-listview')
    # ส่งข้อมูลไปหน้า form
    def get_form_kwargs(self):
        kwargs = super().get_form_kwargs()
        kwargs['id'] = self.kwargs['pk']
        return kwargs
    # ส่งข้อมูลไปหน้า html 
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        # ป้องกัน error user ที่ไม่ได้ login
        try:
            context['user_data'] = UserData.objects.get(user=self.request.user.id)
        except:
            context['user'] = UserData.objects.last()
        return context



class LocationView(ListView):
    model = Location
    context_object_name = 'location'
    template_name = 'location/location-listview.html'
    # ส่งข้อมูลไปหน้า html 
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['rack_equipment'] = RackEquipment.objects.all()
        context['rack'] = Rack.objects.all()
        # ป้องกัน error user ที่ไม่ได้ login
        try:
            context['user_data'] = UserData.objects.get(user=self.request.user.id)
        except:
            context['user'] = UserData.objects.last()
        return context

class deleteLocation(DeleteView):
    model = Location
    success_url = reverse_lazy('location-listview')
    def get(self, request, *args, **kwargs):
        return self.post(request, *args, **kwargs)

blogs/templates/rack/add-rack.html
{% extends 'base.html' %} {% load static %} {% block content %} {% if user.is_superuser %}

<style>
    .rack_error,
    .acceptable_weight_error,
    .rack_weight_error,
    .location_error {
        font-size: 12px;
        color: rgb(255, 0, 0);
    }
</style>
<div style="display: none;">
    {% block title %}Add Rack{% endblock %}
    <input class="menu" value="rack" readonly>
</div>

<!-- ตรวจสอบข้อมูล user ว่ามี่การเพิ่มข้อมูลครบแล้วหรือยัง -->
{% if user_data.first_name == "" or user_data.last_name == "" or user_data.email == "" or user_data.phone == "" or user_data.address == "" or user_data.image == "" %}
<meta http-equiv=refresh content=0;URL="{% url 'profile' user.id %}"> {% endif %}

<div class="container">
    <h2 style="text-align: center">Add Rack</h2>
    <!-- ฟอร์มกรอกข้อมูล -->
    <form method="POST" enctype="multipart/form-data">
        {% csrf_token %} {{ form.as_p }}
        <input type="submit" value="Save" class="btn btn-outline-success btn-block" id="btn-add">
    </form>
</div>

<script src="https://code.jquery.com/jquery-3.4.1.min.js"></script>

<script type="text/javascript">
    // ปรับแต่งฟอร์มกรอกข้อมูล
    setLabel_input = ["Rack", "Acceptable Weight", "Rack Weight", "Rack Size", "Location"]
    setInput_text = ["rack", "acceptable_weight", "rack_weight", "rack_size", "location"]
    var i = 0;
    while (i <= setInput_text.length) {
        $('#id_' + setInput_text[i]).addClass(setInput_text[i] + ' form-control my-0 py-1 lime-border');
        $('.' + setInput_text[i]).after('<label><p id="' + setInput_text[i] + '_error" class="' + setInput_text[i] + '_error"></p></label>');
        $('label[for="id_' + setInput_text[i] + '"]').replaceWith('<label>' + setLabel_input[i] + '</label>');
        i++
    }

    // $('.location').after("<label style='float: right;'><a href='#'" + 'onclick="ShowPopup(' + "'add-location'" + ');">Add Location?</a></label>');

    var location_select = '<select name="location" id="id_location" class="form-control my-0 py-1 lime-border">';
    "{% for x in location_all %}"
    location_select += '<option value="{{x.id}}">{{x.location}}</option>';
    "{% endfor %}"
    location_select += '</select>';
    $('select[id="id_location"]').replaceWith(location_select);
    $('#id_location').val("{{location.id}}");

    var unit = '<select name="rack_size" id="id_rack_size" class="form-control my-0 py-1 lime-border">';
    unit += '<option value="null">---------</option>';
    unit += '<option value="6">6</option>';
    unit += '<option value="9">9</option>';
    unit += '<option value="12">12</option>';
    unit += '<option value="15">15</option>';
    unit += '<option value="27">27</option>';
    unit += '<option value="36">36</option>';
    unit += '<option value="42">42</option>';
    unit += '</select>';
    $('input[id="id_rack_size"]').replaceWith(unit);
</script>

<script type="text/javascript">
    var rack = 0;
    var acceptable_weight = 0;
    var rack_weight = 0;
    var legs_weight = 0;
    var setLocation = 0;
    $(function() {

        // ตรวจสอบข้อมูลอีกครั้งหลังกดปุ่ม submit
        $("#btn-add").click(function() {
            if (validateRack()) {
                $('#id_rack').css("border", "2px solid rgb(252, 0, 0)");
                $("#rack_error").html("ต้องมีตัวอักษรอย่างน้อย 2 ตัว");
                $("#rack_error").show();
                rack = 0;
            } else {
                $('#id_rack').css("border", "2px solid dodgerblue");
                $("#rack_error").hide();
                rack = 1;
            }
            if (validateAcceptable()) {
                $('#id_acceptable_weight').css("border", "2px solid rgb(252, 0, 0)");
                $("#acceptable_weight_error").html("ห้ามต่ำกว่า 0");
                $("#acceptable_weight_error").show();
                acceptable_weight = 0;
            } else {
                $('#id_acceptable_weight').css("border", "2px solid dodgerblue");
                $("#acceptable_weight_error").hide();
                acceptable_weight = 1;
            }
            if (validateRackW()) {
                $('#id_rack_weight').css("border", "2px solid rgb(252, 0, 0)");
                $("#rack_weight_error").html("ห้ามต่ำกว่า 0");
                $("#rack_weight_error").show();
                rack_weight = 0;
            } else {
                $('#id_rack_weight').css("border", "2px solid dodgerblue");
                $("#rack_weight_error").hide();
                rack_weight = 1;
            }
            if ($('#id_location').val() == "") {
                $("#id_location").css("border", "2px solid rgb(255, 0, 0)");
                $("#location_error").html("โปรดเลือก Location");
                $("#location_error").show();
                setLocation = 0;
            } else {
                $("#id_location").css("border", "2px solid dodgerblue");
                $("#location_error").hide();
                setLocation = 1;
            }
            if (rack == 1 && acceptable_weight == 1 &&
                rack_weight == 1 && setLocation == 1)
                return true;
            else
                return false;
        });

        // ตรวจสอบข้อมูลอีกครั้งก่อนกดปุ่ม submit
        $('#id_location').change(function() {
            if ($(this).val() == "") {
                $("#id_location").css("border", "2px solid rgb(255, 0, 0)");
                $("#location_error").html("โปรดเลือก Location");
                $("#location_error").show();
                setLocation = 0;
            } else {
                $("#id_location").css("border", "2px solid dodgerblue");
                $("#location_error").hide();
                setLocation = 1;
            }
        });
        $('#id_rack').keyup(function() {
            if (validateRack()) {
                $('#id_rack').css("border", "2px solid rgb(252, 0, 0)");
                $("#rack_error").html("ต้องมีตัวอักษรอย่างน้อย 2 ตัว");
                $("#rack_error").show();
                rack = 0;
            } else {
                $('#id_rack').css("border", "2px solid dodgerblue");
                $("#rack_error").hide();
                rack = 1;
            }
        });
        $('#id_acceptable_weight').keyup(function() {
            if (validateAcceptable()) {
                $('#id_acceptable_weight').css("border", "2px solid rgb(252, 0, 0)");
                $("#acceptable_weight_error").html("ห้ามต่ำกว่า 0");
                $("#acceptable_weight_error").show();
                acceptable_weight = 0;
            } else {
                $('#id_acceptable_weight').css("border", "2px solid dodgerblue");
                $("#acceptable_weight_error").hide();
                acceptable_weight = 1;
            }
        });
        $('#id_rack_weight').keyup(function() {
            if (validateRackW()) {
                $('#id_rack_weight').css("border", "2px solid rgb(252, 0, 0)");
                $("#rack_weight_error").html("ห้ามต่ำกว่า 0");
                $("#rack_weight_error").show();
                rack_weight = 0;
            } else {
                $('#id_rack_weight').css("border", "2px solid dodgerblue");
                $("#rack_weight_error").hide();
                rack_weight = 1;
            }
        });
        $('#id_legs_weight').keyup(function() {
            if (validateLegs()) {
                $('#id_legs_weight').css("border", "2px solid rgb(252, 0, 0)");
                $("#legs_weight_error").html("ห้ามเท่ากับ 0 หรือต่ำกว่า 0");
                $("#legs_weight_error").show();
                legs_weight = 0;
            } else {
                $('#id_legs_weight').css("border", "2px solid dodgerblue");
                $("#legs_weight_error").hide();
                legs_weight = 1;
            }
        });

        function validateLegs() {
            var weight = $("#id_legs_weight").val();
            if (weight < 0.00) {
                return true;
            } else {
                return false;
            }
        }

        function validateRackW() {
            var weight = $("#id_rack_weight").val();
            if (weight < 0.00 || String(weight) == "") {
                return true;
            } else {
                return false;
            }
        }

        function validateAcceptable() {
            var weight = $("#id_acceptable_weight").val();
            if (weight < 0.00 || String(weight) == "") {
                return true;
            } else {
                return false;
            }
        }

        function validateRack() {
            var rack_length = $("#id_rack").val().length;
            if (rack_length < 2) {
                return true;
            } else {
                return false;
            }
        }
    });
</script>

<script>
    document.getElementById("id_rack").placeholder = "Name";
    document.getElementById("id_acceptable_weight").placeholder = "Acceptable Weight";
    document.getElementById("id_rack_weight").placeholder = "Rack Weight";
    document.getElementById("id_legs_weight").placeholder = "Legs Weight";
</script>

<script>
    document.getElementById("id_rack").required = false;
    document.getElementById("id_acceptable_weight").required = false;
    document.getElementById("id_rack_weight").required = false;
    document.getElementById("id_legs_weight").required = false;
</script>
{% else %}

<meta http-equiv=refresh content=0;URL="{% url 'rack-listview' %}"> {% endif %} {% endblock %}