myProject/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.staticfiles.urls import staticfiles_urlpatterns


urlpatterns = [
    path('accounts/admin/', admin.site.urls, name='superuser'),    
    path('', include('blogs.urls.index')),
    path('ip/', include('blogs.urls.ip')),
    path('', include('blogs.urls.customer')),
    path('equipment/', include('blogs.urls.equipment')),
    path('service/', include('blogs.urls.service')),
    path('', include('blogs.urls.rack')),
    path('superuser/', include('blogs.urls.register')),
    path('accounts/', include('django.contrib.auth.urls')),
    path('api/', include('blogs.urls.api')),
    path('', include('blogs.urls.profile')),
    path('location/', include('blogs.urls.location')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

blogs/models/customer.py
from django.db import models

class Customer(models.Model):
    name = models.CharField(max_length=140, default='')
    email = models.EmailField()
    phone = models.CharField(max_length=140, default='')
    address = models.CharField(max_length=7000, default='')
    def __str__(self):
        return self.name

blogs/models/equipment.py
from django.db import models
from blogs.models.customer import Customer
from django.contrib.auth.models import User
from blogs.models.rack import Rack
from django.dispatch import receiver
from django.db.models.signals import pre_save, pre_delete
import os


class MachineType(models.Model):
    type_machine = models.CharField(max_length=140, default='')
    def __str__(self):
        return self.type_machine
        
class Equipment(models.Model):
    serial_number = models.CharField(max_length=140, default='')
    machine_name = models.CharField(max_length=140, default='')
    machine_type = models.ForeignKey(MachineType, on_delete=models.CASCADE)
    machine_weight = models.FloatField(max_length=140, default='')
    electric_power = models.FloatField(max_length=140, default='')
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    customer = models.ForeignKey(Customer, on_delete=models.CASCADE, blank=True, null=True) 
    image = models.ImageField(default='___/___/')
    code_type = models.CharField(max_length=140, default='', blank=True, null=True)
    code = models.CharField(max_length=1000, default='', blank=True, null=True)
    auto_generate = models.BooleanField(default=True)
    def __str__(self):
        return self.serial_number

class RackEquipment(models.Model):
    equipment = models.ForeignKey(Equipment, on_delete=models.CASCADE)
    front_back = models.CharField(max_length=500, default='')
    rack = models.ForeignKey(Rack, on_delete=models.SET_NULL, blank=True, null=True)
    unit_number = models.CharField(max_length=500, default='')
    def __str__(self):
        return self.unit_number


        
@receiver(pre_save, sender=Equipment)
def delete_old_image(sender, instance, *args, **kwargs):
    if instance.pk:
        existing_image = Equipment.objects.get(pk=instance.pk)
        if instance.image and existing_image.image != instance.image:
            existing_image.image.delete(True)

def _delete_file(path):
    if os.path.isfile(path):
        os.remove(path)

@receiver(pre_delete, sender=Equipment)
def delete_image_pre_delete_product(sender, instance, *args, **kwargs):
    if instance.image:
        _delete_file(instance.image.path)

blogs/models/ip.py
from django.db import models
from datetime import date
from blogs.models.customer import Customer
from django.contrib.auth.models import User
from django.urls import reverse
from blogs.models.equipment import Equipment

class IPNetworkk(models.Model):
    ip_network = models.CharField(max_length=140, default='')
    subnet = models.IntegerField()
    v_lan = models.CharField(max_length=140, default='')
    create_at = models.DateField(default=date.today)
    user = models.ForeignKey(User, on_delete=models.CASCADE)

    def __str__(self):
        return self.ip_network

class IPAddresss(models.Model):
    ip_address = models.CharField(max_length=140, default='')
    description = models.CharField(max_length=500, default='')
    ip_network = models.ForeignKey(IPNetworkk, on_delete=models.CASCADE) 
    equipment = models.ForeignKey(Equipment, on_delete=models.CASCADE) 
    customer = models.ForeignKey(Customer, on_delete=models.CASCADE, blank=True, null=True) 
    create_at = models.DateField(default=date.today)
    update_at = models.DateField(default=date.today)

    def __str__(self):
        return self.ip_address

blogs/forms/ip.py
from django import forms
from blogs.models.ip import IPNetworkk, IPAddresss
from ipaddress import IPv4Address, IPv6Address, ip_network
from netaddr import IPNetwork, IPAddress
from blogs.models.customer import Customer
from ipaddress import ip_network

class UpdateIPNetworkForm(forms.ModelForm):

    # แก้ไขฟอร์ม
    ip_network = forms.CharField()

    class Meta:

        model = IPNetworkk
        fields = (
                    'ip_network',
                    'subnet',
                    'v_lan',
                 )

class AddIPNetworkForm(forms.ModelForm):

    # แก้ไขฟอร์ม
    ip_network = forms.CharField()

    class Meta:

        model = IPNetworkk
        fields = (
                    'ip_network',
                    'subnet',
                    'v_lan',
                 )

    def clean(self, *args, **kwargs):
        ip_network_input = self.cleaned_data.get('ip_network')
        subnet_input = self.cleaned_data.get('subnet')
        Network = IPNetworkk.objects.all()

        validate = 0
        setNetwork = str(ip_network_input) + '/' + str(subnet_input)
        # ตรวจสอบ Error เมื่อเกิด error ถือว่าข้อมูลที่กรอกมาผิด
        try:
            # วนลูปตรวจสอบช่วง และ ip network นี้ซ้ำไหม
            for x in Network:
                getNetwork = str(x.ip_network) + '/' + str(x.subnet)
                
                address = ip_network(setNetwork)
                address2 = ip_network(getNetwork)
                if IPAddress(str(address[0])) in IPNetwork(getNetwork):
                    print('a')
                    validate = 1
                elif IPAddress(str(address[-1])) in IPNetwork(getNetwork):
                    print('b')
                    validate = 1

                elif IPAddress(str(address2[0])) in IPNetwork(setNetwork):
                    print('c')
                    validate = 1
                elif IPAddress(str(address2[-1])) in IPNetwork(setNetwork):
                    print('d')
                    validate = 1
            if validate == 1:
                self._errors['ip_network'] = self.error_class(['**IP Network นี้เคยลงทะเบียนเเล้ว']) 
            else:
                print('success')
        except:
            print('ERROR')
            self._errors['ip_network'] = self.error_class(['**IP Network หรือ Subnet ของท่านไม่ถูกต้อง']) 


class AddIPAddressForm(forms.ModelForm):
    class Meta:
        model = IPAddresss
        fields = (
                    'ip_network',
                    'ip_address',
                    'equipment',
                    'customer',
                    'description',
                 )

    def clean(self, *args, **kwargs):
        ip_network_input = self.cleaned_data.get('ip_network')
        ip_address_input = self.cleaned_data.get('ip_address')
        network = IPNetworkk.objects.get(ip_network=ip_network_input)
        ipnetwork = str(network.ip_network) + '/' + str(network.subnet)
        # ตรวจสอบว่า ip address นี้อยู่ในช่วงของ ip network ไหม
        if IPAddress(ip_address_input) in IPNetwork(ipnetwork):
            # ตรวจสอบว่า ip address นี้เคยใช้แล้วหรือยัง
            if IPAddresss.objects.filter(ip_address=str(ip_address_input)):
                self._errors['ip_network'] = self.error_class(['**IP Address นี้เคยลงทะเบียนเเล้ว']) 
        else:
            self._errors['ip_network'] = self.error_class(['**IP Network และ IP Address ของท่านไม่สอดคล้อง'])
            # ตรวจสอบว่า ip address นี้เป็น network หรือ broadcast ไหม
        if str(ip_address_input) == str(ip_network(ipnetwork)[0]) or str(ip_address_input) == str(ip_network(ipnetwork)[-1]):
            self._errors['ip_network'] = self.error_class(['**ไม่สามารถเพิ่ม Network หรือ Broadcast ได้'])

class DeleteIPAddressForm(forms.ModelForm):

    def __init__(self, *args, **kwargs):
        self.ipnetwork = kwargs.pop('ipnetwork', None)
        super(DeleteIPAddressForm, self).__init__(*args, **kwargs)

    delete_ip = forms.CharField()
    class Meta:
        model = IPAddresss
        fields = (
                    'delete_ip',
                 )

    def save(self, *args, **kwargs):
        ip_address = super(DeleteIPAddressForm, self)
        ip_address_input = self.cleaned_data.get('delete_ip')
        # แยก ip address เป็น array ตามเครื่องหมาย ,
        id_ip_address = ip_address_input.split(',')
        # ตอมสอบว่าความยาวของ array ยาวเท่ากับจำนวน ip address ที่ถูกสร้างไว้ใน ip network นี้ไหม
        if str(len(IPAddresss.objects.filter(ip_network=self.ipnetwork.id))) == str(len(id_ip_address)):
            # ลบ ip address ที่ถูกสร้างไว้ใน ip network นี้ทั้งหมด
            (IPAddresss.objects.filter(ip_network=self.ipnetwork.id)).delete()
        else:
            # วนลูปลบ ip address ตามที่เลือกเอาไว้
            for x in id_ip_address:
                (IPAddresss.objects.get(id=int(x))).delete()
        return ip_address

blogs/views/api.py
from rest_framework import viewsets
from blogs.serializers.equipment import EquipmentSerializers, RackEquipmentSerializers, EquipmentTypeSerializers, RackSerializers
from blogs.serializers.ip import IPNetworkSerializers, IPAddressSerializers
from blogs.serializers.service import ServiceTypeSerializers, ServiceSerializers, ServiceEquipmentSerializers, ServiceIPAddressSerializers
from blogs.serializers.customer import CustomerSerializers
from blogs.models.equipment import Equipment, RackEquipment, MachineType
from blogs.models.rack import Rack
from blogs.models.customer import Customer
from blogs.models.ip import IPNetworkk, IPAddresss
from blogs.models.service import ServiceIPAddress, ServiceEquipment, ServiceType, Service
from django.core.exceptions import SuspiciousOperation
from rest_framework import permissions


class EquipmentSerializersView(viewsets.ModelViewSet):
    queryset = Equipment.objects.all()
    serializer_class = EquipmentSerializers

class RackEquipmentSerializersView(viewsets.ModelViewSet):
    queryset = RackEquipment.objects.all()
    serializer_class = RackEquipmentSerializers

class MachineTypeSerializersView(viewsets.ModelViewSet):
    queryset = MachineType.objects.all()
    serializer_class = EquipmentTypeSerializers
    permission_classes = (permissions.IsAdminUser, )

class RackSerializersView(viewsets.ModelViewSet):
    queryset = Rack.objects.all()
    serializer_class = RackSerializers

###########################################################################

class IPNetworkSerializersView(viewsets.ModelViewSet):
    queryset = IPNetworkk.objects.all()
    serializer_class = IPNetworkSerializers

class IPAddressSerializersView(viewsets.ModelViewSet):
    queryset = IPAddresss.objects.all()
    serializer_class = IPAddressSerializers

###########################################################################

class ServiceTypeSerializersView(viewsets.ModelViewSet):
    queryset = ServiceType.objects.all()
    serializer_class = ServiceTypeSerializers
    permission_classes = (permissions.IsAdminUser, )

class ServiceSerializersView(viewsets.ModelViewSet):
    queryset = Service.objects.all()
    serializer_class = ServiceSerializers

class ServiceEquipmentSerializersView(viewsets.ModelViewSet):
    queryset = ServiceEquipment.objects.all()
    serializer_class = ServiceEquipmentSerializers

class ServiceIPAddressSerializersView(viewsets.ModelViewSet):
    queryset = ServiceIPAddress.objects.all()
    serializer_class = ServiceIPAddressSerializers

###########################################################################

class CustomerSerializersView(viewsets.ModelViewSet):
    queryset = Customer.objects.all()
    serializer_class = CustomerSerializers

blogs/views/customer.py
from django.shortcuts import render, redirect
from django.views.generic import CreateView, UpdateView, ListView, DetailView, DeleteView
from blogs.models.customer import Customer
from blogs.forms.customer import AddCustomerForm, UpdateCustomerForm
from django.urls import reverse_lazy
from django.http import HttpResponseRedirect, JsonResponse, HttpResponse
from blogs.models.user_data import UserData
from blogs.models.equipment import RackEquipment
from blogs.models.ip import IPAddresss
from blogs.models.service import Service


class AddCustomer(CreateView):
    model = Customer
    form_class = AddCustomerForm
    template_name = 'customer/add-customer.html'
    # ส่งข้อมูลไปหน้า html 
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        # ป้องกัน error user ที่ไม่ได้ login
        try:
            context['user_data'] = UserData.objects.get(user=self.request.user.id)
        except:
            context['user'] = UserData.objects.last()
        return context
    # หนดสิ่งที่จะเกิดขึ้นหลังกดปุ่ม submit และหลังจากตรวจสอบข้อมูลในหน้าฟอร์มเสร็จแล้ว
    def form_valid(self, form):
        form.save(True)  
        return HttpResponse('<script type="text/javascript">window.close()</script>')

        
class AddCustomerTemplateView(CreateView):
    model = Customer
    form_class = AddCustomerForm
    success_url = reverse_lazy('customer-listview')
    template_name = 'customer/add-customer-template-view.html'
    # ส่งข้อมูลไปหน้า html 
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        # ป้องกัน error user ที่ไม่ได้ login
        try:
            context['user_data'] = UserData.objects.get(user=self.request.user.id)
        except:
            context['user'] = UserData.objects.last()
        return context

class UpdateCustomerTemplateView(UpdateView):
    model = Customer
    form_class = UpdateCustomerForm
    template_name = 'customer/update-customer.html'
    # เมื่อกดเพิ่มข้อมูลและต้องการให้ไปยังหน้า detail ที่ต้องใช้ id ในการเข้าถึง
    def get_success_url(self): 
        return reverse_lazy('customer-detail', kwargs={'pk': self.kwargs['pk']})
    # ส่งข้อมูลไปหน้า html 
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        # ป้องกัน error user ที่ไม่ได้ login
        try:
            context['user_data'] = UserData.objects.get(user=self.request.user.id)
        except:
            context['user'] = UserData.objects.last()
        return context

class CustomerView(ListView):
    model = Customer
    context_object_name = 'customer'
    template_name = 'customer/customer-listview.html'
    # ส่งข้อมูลไปหน้า html 
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        # ป้องกัน error user ที่ไม่ได้ login
        try:
            context['user_data'] = UserData.objects.get(user=self.request.user.id)
        except:
            context['user'] = UserData.objects.last()
        return context

class deleteCustomer(DeleteView):
    model = Customer
    success_url = reverse_lazy('customer-listview')
    def get(self, request, *args, **kwargs):
        return self.post(request, *args, **kwargs)
        
class CustomerDetail(DetailView):
    model = Customer
    context_object_name = 'customer'
    template_name = 'customer/customer-detail.html'
    # ส่งข้อมูลไปหน้า html 
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['rackequipment'] = RackEquipment.objects.filter(equipment__customer=self.kwargs['pk'])
        context['ip_address'] = IPAddresss.objects.filter(customer=self.kwargs['pk'])
        context['service'] = Service.objects.filter(customer=self.kwargs['pk'])
        # ป้องกัน error user ที่ไม่ได้ login
        try:
            context['user_data'] = UserData.objects.get(user=self.request.user.id)
        except:
            context['user'] = UserData.objects.last()
        return context

blogs/views/index.py
from django.shortcuts import render, redirect
from django.views.generic import CreateView, UpdateView, ListView, TemplateView
from blogs.models.ip import IPNetworkk
from blogs.models.equipment import Equipment, RackEquipment
from blogs.models.service import Service
from blogs.models.rack import Rack
from blogs.models.user_data import UserData
from django.contrib.auth.models import User
from blogs.models.location import Location

class IndexView(TemplateView):
    template_name = 'index.html'
    # ส่งข้อมูลไปหน้า html 
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        try:
            if not UserData.objects.filter(user=self.request.user.id):
                UserData(user=User.objects.get(id=self.request.user.id)).save()
        except:
            print("pleass login")
        context['ipnetwork'] = IPNetworkk.objects.all()
        context['equipment'] = Equipment.objects.all()
        context['rackequipment'] = RackEquipment.objects.all()
        context['service'] = Service.objects.all()
        context['rack'] = Rack.objects.all()
        context['location'] = Location.objects.all()
        try:
            context['user_data'] = UserData.objects.get(user=self.request.user.id)
        except:
            context['user'] = UserData.objects.last()
        return context

class LinkLoginRegisterView(TemplateView):
    template_name = 'link-login-register.html'

blogs/templates/ip/add-address.html
{% extends 'base.html' %} {% load static %} {% block content %} {% if user.is_superuser %}
<style>
    .ip_network_error,
    .ip_address_error,
    .description_error,
    .equipment_error {
        font-size: 12px;
        color: rgb(255, 0, 0);
    }
</style>
<div style="display: none;">
    {% block title %}Add IP Address{% endblock %}
</div>

<!-- ตรวจสอบข้อมูล user ว่ามี่การเพิ่มข้อมูลครบแล้วหรือยัง -->
{% if user_data.first_name == "" or user_data.last_name == "" or user_data.email == "" or user_data.phone == "" or user_data.address == "" or user_data.image == "" %}
<meta http-equiv=refresh content=0;URL="{% url 'profile' user.id %}"> {% endif %}

<div class="container">
    <h2 style="text-align: center">Add IPAddress</h2>
    <!-- ฟอร์มกรอกข้อมูล -->
    <form method="POST" enctype="multipart/form-data">
        {% csrf_token %} {{ form.as_p }}
        <input type="submit" value="Save" class="btn btn-outline-success btn-block" id="btn-add">
    </form>
</div>

<script src="https://code.jquery.com/jquery-3.4.1.min.js"></script>

<script type="text/javascript">
    // ปรับแต่งฟอร์มกรอกข้อมูล
    setLabel_input = ["IP Network", "IP Address", "Description", "Equipment", "Customer"]
    setInput_text = ["ip_network", "ip_address", "description", "equipment", "customer"]
    var i = 0;
    while (i <= setInput_text.length) {
        $('#id_' + setInput_text[i]).addClass(setInput_text[i] + ' form-control my-0 py-1 lime-border');
        $('label[for="id_' + setInput_text[i] + '"]').replaceWith('<label>' + setLabel_input[i] + '</label>');
        if (setInput_text[i] != "customer") {
            $('.' + setInput_text[i]).after('<label><p id="' + setInput_text[i] + '_error" class="' + setInput_text[i] + '_error"></p></label>');
        } else {
            $('.' + setInput_text[i]).after("<label style='float: right;'><a href='#' id='addCustomer'" + 'onclick="ShowPopup(' + "'add-customer'" + ');">Add Customer?</a></label>');
        }
        i++
    }
    var select = '<select name="ip_network" id="id_ip_network" class="ip_network form-control my-0 py-1 lime-border" style="border: 2px solid rgb(252, 0, 0);">';
    select += '<option value="{{ipnetwork.id}}">{{ipnetwork.ip_network}}</option>';
    select += '</select>';
    $('select[id="id_ip_network"]').replaceWith(select);
</script>

<script type="text/javascript">
    $('document').ready(function() {
        $('#id_ip_address').val(localStorage.getItem('ip_address'));
        $('#id_description').val(localStorage.getItem('description'));
        $('#id_equipment').val(localStorage.getItem('equipment'));
        $('#id_customer').val(localStorage.getItem('customer'));
    });

    var network = 1;
    var address = 1;
    var discription = 0;
    var equipment = 0;
    $(function() {

        $('#id_ip_network').css("border", "2px solid dodgerblue");

        // ตรวจสอบข้อมูลอีกครั้งหลังกดปุ่ม submit
        $("#btn-add").click(function() {
            if (validateNetwork()) {
                $('#id_ip_network').css("border", "2px solid rgb(252, 0, 0)");
                $("#ip_network_error").html("โปรดเลือก IP Network");
                $("#ip_network_error").show();
                network = 0;
            } else {
                $('#id_ip_network').css("border", "2px solid dodgerblue");
                $("#ip_network_error").hide();
                network = 1;
            }
            if (validateAddress()) {
                $('#id_ip_address').css("border", "2px solid rgb(252, 0, 0)");
                $("#ip_address_error").html("IP Address ของท่านไม่ถูกต้อง");
                $("#ip_address_error").show();
                address = 0;
            } else {
                $('#id_ip_address').css("border", "2px solid dodgerblue");
                $("#ip_address_error").hide();
                address = 1;
            }
            if (validateDescription()) {
                $('#id_description').css("border", "2px solid rgb(252, 0, 0)");
                $("#description_error").html("กรุณากรอกข้อมูล");
                $("#description_error").show();
                discription = 0;
            } else {
                $('#id_description').css("border", "2px solid dodgerblue");
                $("#description_error").hide();
                discription = 1;
            }
            if (validateEquipment()) {
                $('#id_equipment').css("border", "2px solid rgb(252, 0, 0)");
                $("#equipment_error").html("โปรดเลือก Equipment");
                $("#equipment_error").show();
                equipment = 0;
            } else {
                $('#id_equipment').css("border", "2px solid dodgerblue");
                $("#equipment_error").hide();
                equipment = 1;
            }
            $('#id_customer').css("border", "2px solid dodgerblue");
            if (network == 1 && address == 1 && discription == 1 && equipment == 1)
                return true;
            else
                return false;
        });

        // ตรวจสอบข้อมูลอีกครั้งก่อนกดปุ่ม submit
        $('#id_ip_network').click(function() {
            if (validateNetwork()) {
                $('#id_ip_network').css("border", "2px solid rgb(252, 0, 0)");
                $("#ip_network_error").html("โปรดเลือก IP Network");
                $("#ip_network_error").show();
                network = 0;
            } else {
                $('#id_ip_network').css("border", "2px solid dodgerblue");
                $("#ip_network_error").hide();
                network = 1;
            }
        });
        $('#id_ip_address').keyup(function() {
            if (validateAddress()) {
                $('#id_ip_address').css("border", "2px solid rgb(252, 0, 0)");
                $("#ip_address_error").html("IP Address ของท่านไม่ถูกต้อง");
                $("#ip_address_error").show();
                address = 0;
            } else {
                $('#id_ip_address').css("border", "2px solid dodgerblue");
                $("#ip_address_error").hide();
                localStorage.setItem('ip_address', $(this).val());
                address = 1;
            }
        });
        $('#id_description').keyup(function() {
            if (validateDescription()) {
                $('#id_description').css("border", "2px solid rgb(252, 0, 0)");
                $("#description_error").html("กรุณากรอกข้อมูล");
                $("#description_error").show();
                discription = 0;
            } else {
                $('#id_description').css("border", "2px solid dodgerblue");
                $("#description_error").hide();
                localStorage.setItem('description', $(this).val());
                discription = 1;
            }
        });
        $('#id_equipment').click(function() {
            if (validateEquipment()) {
                $('#id_equipment').css("border", "2px solid rgb(252, 0, 0)");
                $("#equipment_error").html("โปรดเลือก Equipment");
                $("#equipment_error").show();
                equipment = 0;
            } else {
                $('#id_equipment').css("border", "2px solid dodgerblue");
                $("#equipment_error").hide();
                localStorage.setItem('equipment', $(this).val());
                equipment = 1;
            }
        });
        $('#id_customer').click(function() {
            $('#id_customer').css("border", "2px solid dodgerblue");
            localStorage.setItem('customer', $(this).val());
        });

        function validateEquipment() {
            var equipment = $("#id_equipment").val();
            if (equipment == "") {
                return true;
            } else {
                return false;
            }
        }

        function validateNetwork() {
            var network = $("#id_ip_network").val();
            if (network == "") {
                return true;
            } else {
                return false;
            }
        }

        function validateAddress() {
            var address = $("#id_ip_address").val();
            var reg = /((^\s*((([0-9]|[1-9][0-9]|1[0-9]{2}|2[0-4][0-9]|25[0-5])\.){3}([0-9]|[1-9][0-9]|1[0-9]{2}|2[0-4][0-9]|25[0-5]))\s*$)|(^\s*((([0-9A-Fa-f]{1,4}:){7}([0-9A-Fa-f]{1,4}|:))|(([0-9A-Fa-f]{1,4}:){6}(:[0-9A-Fa-f]{1,4}|((25[0-5]|2[0-4]\d|1\d\d|[1-9]?\d)(\.(25[0-5]|2[0-4]\d|1\d\d|[1-9]?\d)){3})|:))|(([0-9A-Fa-f]{1,4}:){5}(((:[0-9A-Fa-f]{1,4}){1,2})|:((25[0-5]|2[0-4]\d|1\d\d|[1-9]?\d)(\.(25[0-5]|2[0-4]\d|1\d\d|[1-9]?\d)){3})|:))|(([0-9A-Fa-f]{1,4}:){4}(((:[0-9A-Fa-f]{1,4}){1,3})|((:[0-9A-Fa-f]{1,4})?:((25[0-5]|2[0-4]\d|1\d\d|[1-9]?\d)(\.(25[0-5]|2[0-4]\d|1\d\d|[1-9]?\d)){3}))|:))|(([0-9A-Fa-f]{1,4}:){3}(((:[0-9A-Fa-f]{1,4}){1,4})|((:[0-9A-Fa-f]{1,4}){0,2}:((25[0-5]|2[0-4]\d|1\d\d|[1-9]?\d)(\.(25[0-5]|2[0-4]\d|1\d\d|[1-9]?\d)){3}))|:))|(([0-9A-Fa-f]{1,4}:){2}(((:[0-9A-Fa-f]{1,4}){1,5})|((:[0-9A-Fa-f]{1,4}){0,3}:((25[0-5]|2[0-4]\d|1\d\d|[1-9]?\d)(\.(25[0-5]|2[0-4]\d|1\d\d|[1-9]?\d)){3}))|:))|(([0-9A-Fa-f]{1,4}:){1}(((:[0-9A-Fa-f]{1,4}){1,6})|((:[0-9A-Fa-f]{1,4}){0,4}:((25[0-5]|2[0-4]\d|1\d\d|[1-9]?\d)(\.(25[0-5]|2[0-4]\d|1\d\d|[1-9]?\d)){3}))|:))|(:(((:[0-9A-Fa-f]{1,4}){1,7})|((:[0-9A-Fa-f]{1,4}){0,5}:((25[0-5]|2[0-4]\d|1\d\d|[1-9]?\d)(\.(25[0-5]|2[0-4]\d|1\d\d|[1-9]?\d)){3}))|:)))(%.+)?\s*$))/
            if (reg.test(address)) {
                return false;
            } else {
                return true;
            }
        }

        function validateDescription() {
            var description = $("#id_description").val();
            if (description == "") {
                return true;
            } else {
                return false;
            }
        }
    });
</script>

<script>
    var i = 1;
    document.getElementById('id_ip_network')[0].style.display = "none";
    "{% for network in network %}"
    if ("{{ id }}" == "{{ network.id }}") {
        document.getElementById('id_ip_network')[i].style.display = "block";
        document.getElementById('id_ip_network')[i].selected = true;
    } else
        document.getElementById('id_ip_network')[i].style.display = "none";
    i++;
    "{% endfor %}"
</script>

<script>
    document.getElementById("id_ip_address").placeholder = "192.168.1.1";
    document.getElementById("id_description").placeholder = "????????????";
</script>

<script>
    document.getElementById("id_ip_network").required = false;
    document.getElementById("id_ip_address").required = false;
    document.getElementById("id_discription").required = false;
</script>

<script type="text/javascript ">
    // โชว์ popup 
    var popup;

    function ShowPopup(url) {
        popup = window.open(url, "Popup ", "toolbar=no,scrollbars=no,location=no,statusbar=no,menubar=no,resizable=0,width=500,height=540,left=4 90,top=2 62 ");
        popup.focus();
    }
</script>

{% else %}

<meta http-equiv=refresh content=0;URL="{% url 'ip-listview' %}"> {% endif %} {% endblock %}